/* Administration (ToR §6 administration and control, ADM-01..03): role-based tabs, four-eyes verification,
   no-code geography / emergency / content / flags, import/export, audit, reports, complaints, Han's orders. */
const ADMIN = (() => {
  const { esc, $, $$ } = UI;
  const TABS = [
    ['overview','adm_reports',['admin','verifier','safety','privacy','finance']],
    ['verif','adm_verif',['admin','verifier']],
    ['geo','adm_geo',['admin']],
    ['emergency','adm_emergency',['admin','safety']],
    ['content','adm_content',['admin','safety']],
    ['flags','adm_flags',['admin','safety']],
    ['complaints','adm_complaints',['admin','safety','privacy']],
    ['hans','prod_title',['admin','finance']],
    ['fees','adm_fees',['admin','finance']],
    ['audit','adm_audit',['admin','privacy']],
    ['users','adm_users',['admin']]
  ];
  function view() {
    const s = PRO.requireRole(['admin','verifier','safety','privacy','finance']); if (!s) return;
    const tabs = TABS.filter(x => x[2].includes(s.role)); const tab = UI.qs().tab || tabs[0][0];
    if (!tabs.find(x => x[0] === tab)) return UI.go('#/admin');
    UI.render(PRO.head(s) + '<div class="tabs" role="tablist">' + tabs.map(x => '<button role="tab" data-tab="' + x[0] + '" aria-selected="' + (tab === x[0]) + '">' + esc(t(x[1])) + '</button>').join('') + '</div><div id="adm"></div>', { title: t('adm_title') });
    PRO.bindHead();
    $$('[data-tab]').forEach(b => b.onclick = () => UI.go('#/admin?tab=' + b.getAttribute('data-tab')));
    ({ overview, verif, geo, emergency, content, flags, complaints, hans, fees, audit, users })[tab](s, $('#adm'));
  }
  const table = (rows, cols, actions) => '<div class="scroll-x"><table class="tbl"><tr>' + cols.map(c => '<th>' + esc(c[0]) + '</th>').join('') + (actions ? '<th></th>' : '') + '</tr>' + rows.map(r => '<tr>' + cols.map(c => '<td>' + (typeof c[1] === 'function' ? c[1](r) : esc(r[c[1]])) + '</td>').join('') + (actions ? '<td>' + actions(r) + '</td>' : '') + '</tr>').join('') + '</table></div>';

  function overview(s, el) {
    const cs = DB.all('cases'), os = DB.all('orders'); const by = (arr, k) => arr.reduce((m, x) => { const v = typeof k === 'function' ? k(x) : x[k]; m[v] = (m[v] || 0) + 1; return m; }, {});
    const resp = cs.filter(c => c.timeline.some(x => x.state === 'accepted' || x.state === 'under_review')).map(c => { const a = c.timeline.find(x => x.state === 'accepted' || x.state === 'under_review'); return (new Date(a.at) - new Date(c.createdAt)) / 60000; }).sort((a, b) => a - b);
    const med = resp.length ? resp[Math.floor(resp.length / 2)].toFixed(0) + ' min' : '-'; const p90 = resp.length ? resp[Math.floor(resp.length * 0.9)].toFixed(0) + ' min' : '-';
    const prs = DB.all('practitioners'), fac = DB.all('facilities'), em = DB.all('emergency'), pp = DB.all('pharmacyProducts');
    const expiring = prs.filter(p => { const d = UI.daysUntil(p.licence.expiry); return d !== null && d < 60; }).length;
    const emDue = em.filter(e => e.status !== 'verified' || (e.reviewDue && UI.daysUntil(e.reviewDue) < 0)).length;
    const staleStock = pp.filter(p => (Date.now() - new Date(p.updatedAt)) > 72 * 3600e3 && p.stock !== 'not_stocked').length;
    const k = (n, l) => '<div class="kpi"><div class="n">' + n + '</div><div class="l">' + esc(l) + '</div></div>';
    el.innerHTML = '<div class="kpis">' + k(cs.length, t('my_requests')) + k(cs.filter(c => /received|submitted|under_review|clarification_requested/.test(c.state)).length, t('adm_pending')) + k(cs.filter(c => c.redFlag).length, t('red_flag')) + k(os.length, t('my_orders')) + k(prs.filter(p => p.verification.state === 'pending').length + fac.filter(f => f.verification.state === 'pending').length, t('adm_verif') + ' · ' + t('adm_pending')) + k(expiring, t('pro_expiring')) + k(emDue, t('adm_emergency') + ' · due') + k(staleStock, t('pro_stale')) + k(med + ' / ' + p90, 'Response median / p90') + k(cs.filter(c => c.state === 'queued_offline').length, t('st_queued')) + '</div>' +
      '<div class="grid2"><div class="card"><h3>By channel</h3>' + table(Object.entries(by(cs, 'channel')).map(x => ({ k: x[0], n: x[1] })), [['Channel','k'],['n','n']]) + '</div><div class="card"><h3>By language</h3>' + table(Object.entries(by(cs, 'lang')).map(x => ({ k: x[0], n: x[1] })), [['Lang','k'],['n','n']]) + '</div><div class="card"><h3>By state</h3>' + table(Object.entries(by(cs, 'state')).map(x => ({ k: x[0], n: x[1] })), [['State','k'],['n','n']]) + '</div><div class="card"><h3>By region</h3>' + table(Object.entries(by(cs, c => { const r = c.location && c.location.adminUnit ? GEO.regionOf(c.location.adminUnit) : null; return r ? r.name : '-'; })).map(x => ({ k: x[0], n: x[1] })), [['Region','k'],['n','n']]) + '</div></div>' +
      '<div class="card"><h3>Guide log (' + DB.all('guideLog').length + ')</h3>' + table(Object.entries(by(DB.all('guideLog'), 'kind')).map(x => ({ k: x[0], n: x[1] })), [['Kind','k'],['n','n']]) + '<p class="hint">Privacy-preserving: counts only, no message text stored (ToR §15). Small cells should be suppressed in exports.</p></div>' +
      '<div class="row"><button class="btn ghost small" id="expAll">⬇ ' + esc(t('adm_export')) + ' JSON</button>' + (s.role === 'admin' ? '<button class="btn danger small" id="resetDemo">' + esc(t('adm_reset')) + '</button>' : '') + '</div>';
    $('#expAll').onclick = () => { DB.audit('export:all'); UI.download('hwc-export.json', DB.exportJSON(), 'application/json'); };
    const r = $('#resetDemo'); if (r) r.onclick = () => UI.confirm(t('adm_reset') + '?', () => DB.reset());
  }

  // Four-eyes verification (ADM-01): two different administrators/verifiers must approve before "verified".
  function verif(s, el) {
    const items = [].concat(DB.all('practitioners').map(p => ({ col: 'practitioners', o: p, kind: 'practitioner', name: p.name, detail: p.profession + ' · ' + p.licence.no + ' · ' + p.licence.issuer + ' · exp ' + p.licence.expiry })), DB.all('facilities').map(f => ({ col: 'facilities', o: f, kind: f.type, name: f.name, detail: (f.licence && f.licence.no ? f.licence.no + ' · exp ' + f.licence.expiry : f.licence.status) + (f.responsiblePharmacist ? ' · ' + f.responsiblePharmacist : '') })), DB.all('wellbeing').map(w => ({ col: 'wellbeing', o: w, kind: 'wellbeing', name: w.name, detail: w.service })));
    const pending = items.filter(x => x.o.verification.state !== 'verified' && x.o.verification.state !== 'rejected' && x.o.verification.state !== 'revoked');
    const exp = items.filter(x => x.o.verification.state === 'verified' && x.o.licence && x.o.licence.expiry && UI.daysUntil(x.o.licence.expiry) < 60);
    const appr = id => (DB.all('approvals').find(a => a.object === id) || { approvers: [] });
    const row = x => { const a = appr(x.o.id); return '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(x.name) + ' <span class="badge b-grey">' + esc(x.kind) + '</span></span>' + UI.verifBadge(x.o.verification) + '</div><div class="meta">' + esc(x.detail) + '</div><div class="meta">' + esc(t('adm_evidence')) + ': ' + esc(x.o.verification.evidence || '-') + (a.approvers.length ? ' · 1/2 ✓ ' + esc(a.approvers.map(u => (DB.get('users', u) || DB.all('profiles').find(p => p.user_id === u) || { name: u.slice(0, 8) }).name).join(', ')) : '') + '</div><div class="row" style="margin-top:6px"><button class="btn small success" data-ap="' + x.o.id + '" data-col="' + x.col + '"' + (a.approvers.includes(s.id) ? ' disabled' : '') + '>' + esc(t('adm_approve')) + '</button><button class="btn small danger" data-rj="' + x.o.id + '" data-col="' + x.col + '">' + esc(t('adm_reject')) + '</button><button class="btn small ghost" data-ev="' + x.o.id + '" data-col="' + x.col + '">' + esc(t('adm_evidence')) + '</button></div></div></div>'; };
    el.innerHTML = '<p class="hint">' + esc(t('adm_four_eyes')) + '. Statutory licensing sources (MOH HRL, regional bureaus, EFDA) are the legal basis; associations only support validation (ToR §12).</p><h3>' + esc(t('adm_pending')) + ' (' + pending.length + ')</h3><div class="card">' + (pending.length ? pending.map(row).join('') : '<p class="muted">' + esc(t('pro_no_items')) + '</p>') + '</div><h3>' + esc(t('pro_expiring')) + ' (' + exp.length + ')</h3><div class="card">' + (exp.length ? exp.map(x => '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(x.name) + '</span><span class="badge b-amber">' + esc(x.o.licence.expiry) + '</span></div><div class="row" style="margin-top:6px"><button class="btn small danger" data-sus="' + x.o.id + '" data-col="' + x.col + '">Suspend</button></div></div></div>').join('') : '<p class="muted">' + esc(t('pro_no_items')) + '</p>') + '</div><h3>' + esc(t('verified')) + '</h3><div class="card">' + items.filter(x => x.o.verification.state === 'verified').map(x => '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(x.name) + '</span>' + UI.verifBadge(x.o.verification) + '</div><div class="meta">' + esc(x.detail) + '</div><div class="row" style="margin-top:6px"><button class="btn small ghost" data-sus="' + x.o.id + '" data-col="' + x.col + '">Suspend</button></div></div></div>').join('') + '</div>';
    $$('[data-ap]').forEach(b => b.onclick = () => { const id = b.getAttribute('data-ap'), col = b.getAttribute('data-col'); let a = DB.all('approvals').find(x => x.object === id); if (!a) a = { id: DB.newId('AP'), object: id, approvers: [] }; if (a.approvers.includes(s.id)) return; a.approvers.push(s.id); DB.put('approvals', a); DB.audit('verify:approve', id); if (a.approvers.length >= 2) { const o = DB.get(col, id); o.verification = { state: 'verified', verifiedAt: DB.nowIso(), by: a.approvers.join('+'), evidence: o.verification.evidence }; DB.put(col, o); DB.audit('verify:verified', id); UI.toast(t('verified')); } else UI.toast(t('adm_first_approval'), 4000); view(); });
    $$('[data-rj]').forEach(b => b.onclick = () => PRO.reason(t('adm_reject'), r => { const o = DB.get(b.getAttribute('data-col'), b.getAttribute('data-rj')); o.verification = { state: 'rejected', verifiedAt: null, by: s.id, evidence: r }; DB.put(b.getAttribute('data-col'), o); DB.audit('verify:reject', o.id, { reason: r }); view(); }));
    $$('[data-ev]').forEach(b => b.onclick = () => PRO.reason(t('adm_evidence'), r => { const o = DB.get(b.getAttribute('data-col'), b.getAttribute('data-ev')); o.verification.evidence = r; o.verification.state = 'pending'; DB.put(b.getAttribute('data-col'), o); DB.audit('verify:evidence', o.id); view(); }));
    $$('[data-sus]').forEach(b => b.onclick = () => PRO.reason('Suspend', r => { const o = DB.get(b.getAttribute('data-col'), b.getAttribute('data-sus')); o.verification = { state: 'suspended', verifiedAt: o.verification.verifiedAt, by: s.id, evidence: r }; if (o.availability) o.availability = 'offline_mode'; DB.put(b.getAttribute('data-col'), o); DB.remove('approvals', (DB.all('approvals').find(x => x.object === o.id) || {}).id); DB.audit('verify:suspend', o.id, { reason: r }); view(); }));
  }

  function geo(s, el) {
    const lang = getLang(); let q = '';
    const draw = () => { const rows = DB.all('geo').filter(u => u.level > 0 && (!q || (u.name + ' ' + u.local + ' ' + u.id + ' ' + (u.aliases || []).join(' ')).toLowerCase().includes(q))).slice(0, 300); $('#geoList').innerHTML = table(rows, [['ID','id'],['Level',u => u.level],['Name',u => esc(u.name) + (u.local ? '<br><small>' + esc(u.local) + '</small>' : '')],['Parent',u => esc(u.parent)],['Geom',u => u.lat != null ? u.lat.toFixed(3) + ', ' + u.lng.toFixed(3) + '<br><small>' + esc(u.geomConfidence || '') + '</small>' : '-'],['Source / version',u => esc(u.source) + '<br><small>' + esc(u.version) + '</small>'],['Verified',u => u.verifiedAt ? esc(UI.fmtDate(u.verifiedAt)) : '<span class="badge b-amber">' + esc(t('adm_pending')) + '</span>'],['Active',u => u.active === false ? 'no' : 'yes']], u => '<button class="btn small ghost" data-ed="' + u.id + '">' + esc(t('edit')) + '</button>'); $$('[data-ed]').forEach(b => b.onclick = () => editUnit(DB.get('geo', b.getAttribute('data-ed')))); };
    el.innerHTML = '<p class="hint">Flexible hierarchy Country → Region → Zone → Woreda → Sub-city → Kebele → locality (ToR §8). Every unit carries source, version, verification and change history. Replace the seed with authority-validated data via CSV import; no code release needed.</p><div class="row"><input type="search" id="gq" class="in" style="flex:1" placeholder="' + esc(t('search')) + '"><button class="btn small" id="gAdd">+ ' + esc(t('adm_add')) + '</button><button class="btn small ghost" id="gCsv">⬇ CSV</button><button class="btn small ghost" id="gGeo">⬇ GeoJSON</button><label class="btn small ghost">⬆ ' + esc(t('adm_import')) + '<input type="file" id="gImp" accept=".csv" hidden></label></div><p class="small muted">' + DB.all('geo').length + ' units · ' + esc(SEED.version) + '</p><div id="geoList"></div>';
    draw();
    $('#gq').oninput = e => { q = e.target.value.toLowerCase(); draw(); };
    $('#gAdd').onclick = () => editUnit({ id: '', level: 6, parent: '', name: '', local: '', aliases: [], lat: null, lng: null, urban: true, geomConfidence: 'unknown', source: '', sourceUrl: '', version: DB.nowIso().slice(0, 10), obtained: DB.nowIso().slice(0, 10), verifiedAt: null, verifiedBy: null, active: true });
    $('#gCsv').onclick = () => { DB.audit('export:geo'); UI.download('hwc-gazetteer.csv', DB.toCSV(DB.all('geo').map(u => Object.assign({}, u, { aliases: (u.aliases || []).join('|') })), ['id','level','parent','name','local','aliases','lat','lng','urban','geomConfidence','source','sourceUrl','version','obtained','verifiedAt','verifiedBy','active','pack']), 'text/csv'); };
    $('#gGeo').onclick = () => { DB.audit('export:geojson'); UI.download('hwc-gazetteer.geojson', JSON.stringify({ type: 'FeatureCollection', features: DB.all('geo').filter(u => u.lat != null).map(u => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [u.lng, u.lat] }, properties: { id: u.id, level: u.level, parent: u.parent, name: u.name, local: u.local, source: u.source, version: u.version, verifiedAt: u.verifiedAt, confidence: u.geomConfidence } })) }), 'application/geo+json'); };
    $('#gImp').onchange = e => importCSV(e.target.files[0], 'geo', r => ({ id: r.id, level: +r.level, parent: r.parent || null, name: r.name, local: r.local || '', aliases: (r.aliases || '').split('|').filter(Boolean), lat: r.lat ? +r.lat : null, lng: r.lng ? +r.lng : null, urban: r.urban === 'true', geomConfidence: r.geomConfidence || 'imported', source: r.source || 'import', sourceUrl: r.sourceUrl || '', version: r.version || DB.nowIso().slice(0, 10), obtained: r.obtained || DB.nowIso().slice(0, 10), verifiedAt: r.verifiedAt || null, verifiedBy: r.verifiedBy || null, active: r.active !== 'false', pack: r.pack || null }), u => u.id && u.name && !isNaN(u.level));
    function editUnit(u) {
      UI.modal('<h2>' + esc(t('adm_geo')) + '</h2>' + [['id','ID'],['name','Name (official)'],['local','Local-script name'],['aliases','Aliases (| separated)'],['parent','Parent ID'],['level','Level (1-6)'],['lat','Lat'],['lng','Lng'],['source','Source'],['sourceUrl','Source URL'],['version','Version']].map(x => '<label class="f">' + esc(x[1]) + '<input type="text" id="gf_' + x[0] + '" value="' + esc(x[0] === 'aliases' ? (u.aliases || []).join('|') : (u[x[0]] == null ? '' : u[x[0]])) + '"' + (x[0] === 'id' && u.id ? ' readonly' : '') + '></label>').join('') + '<label class="check"><input type="checkbox" id="gf_active"' + (u.active !== false ? ' checked' : '') + '><span>Active</span></label><label class="check"><input type="checkbox" id="gf_ver"' + (u.verifiedAt ? ' checked' : '') + '><span>Verified with competent administration</span></label><div class="row" style="margin-top:8px"><button class="btn primary" id="gfOk">' + esc(t('save')) + '</button><button class="btn ghost" data-close>' + esc(t('cancel')) + '</button></div>', (el2, close) => { $('#gfOk', el2).onclick = () => { const g = k => $('#gf_' + k, el2).value.trim(); const n = Object.assign({}, u, { id: g('id').toUpperCase(), name: g('name'), local: g('local'), aliases: g('aliases').split('|').filter(Boolean), parent: g('parent').toUpperCase() || null, level: +g('level'), lat: g('lat') ? +g('lat') : null, lng: g('lng') ? +g('lng') : null, source: g('source'), sourceUrl: g('sourceUrl'), version: g('version'), active: $('#gf_active', el2).checked }); if (!n.id || !n.name) return; if ($('#gf_ver', el2).checked && !u.verifiedAt) { n.verifiedAt = DB.nowIso(); n.verifiedBy = s.id; } if (!$('#gf_ver', el2).checked) { n.verifiedAt = null; n.verifiedBy = null; } n.history = (u.history || []).concat([{ at: DB.nowIso(), by: s.id, prev: { name: u.name, parent: u.parent, active: u.active } }]); DB.put('geo', n); DB.audit('geo:save', n.id); close(); view(); }; });
    }
  }
  function importCSV(file, col, map, valid) {
    if (!file) return; file.text().then(txt => { const rows = DB.parseCSV(txt).map(map); const ok = rows.filter(valid); const bad = rows.length - ok.length; const existing = DB.all(col); let added = 0, updated = 0; ok.forEach(r => { if (existing.find(x => x.id === r.id)) updated++; else added++; DB.put(col, r); }); DB.audit('import:' + col, file.name, { result: added + ' added, ' + updated + ' updated, ' + bad + ' rejected' }); UI.toast(added + ' added · ' + updated + ' updated · ' + bad + ' rejected', 5000); view(); });
  }

  function emergency(s, el) {
    const lang = getLang(); const em = DB.all('emergency');
    el.innerHTML = '<p class="hint">Jurisdiction-specific, versioned public-safety records (ToR §8, Annex D). A record is public only when its owner confirmed it; overdue records are flagged and an owner-marked invalid record is hidden.</p><div class="row"><button class="btn small" id="eAdd">+ ' + esc(t('adm_add')) + '</button><button class="btn small ghost" id="eCsv">⬇ CSV</button><label class="btn small ghost">⬆ ' + esc(t('adm_import')) + '<input type="file" id="eImp" accept=".csv" hidden></label></div>' + table(em, [['Jurisdiction',e => esc(GEO.label(GEO.unit(e.jurisdiction), lang) || e.jurisdiction)],['Service',e => esc(e.label) + '<br><small>' + esc(e.service) + '</small>'],['Phone',e => '<b>' + esc(e.primary || '-') + '</b>' + (e.backup ? ' / ' + esc(e.backup) : '')],['Owner / source',e => esc(e.owner) + '<br><small>' + esc(e.source) + '</small>'],['Status',e => (e.status === 'verified' ? '<span class="badge b-green">' + esc(t('verified')) + '</span>' : e.status === 'source-checked' ? '<span class="badge b-amber">source-checked</span>' : e.status === 'hidden' || e.status === 'invalid' ? '<span class="badge b-red">' + esc(e.status) + '</span>' : '<span class="badge b-amber">' + esc(t('adm_pending')) + '</span>') + (e.reviewDue && UI.daysUntil(e.reviewDue) < 0 ? '<br><span class="badge b-red">review overdue</span>' : '')],['Verified / due',e => esc(e.verifiedAt ? UI.fmtDate(e.verifiedAt) : '-') + '<br><small>' + esc(e.reviewDue || '') + '</small>']], e => '<div class="row"><button class="btn small ghost" data-eed="' + e.id + '">' + esc(t('edit')) + '</button><button class="btn small success" data-erev="' + e.id + '">' + esc(t('adm_revalidate')) + '</button><button class="btn small danger" data-ehide="' + e.id + '">' + esc(t('adm_hide')) + '</button></div>');
    const edit = e => UI.modal('<h2>' + esc(t('adm_emergency')) + '</h2>' + [['jurisdiction','Jurisdiction ID (ET, AA, OR…)'],['service','Service (police/ambulance/fire/hospital/poison/gbv/mental)'],['label','Public label'],['primary','Primary number (exact dial format)'],['backup','Backup number'],['hours','Hours'],['owner','Owning agency'],['source','Evidence / source'],['sourceUrl','Source URL'],['reviewDue','Next review (YYYY-MM-DD)']].map(x => '<label class="f">' + esc(x[1]) + '<input type="text" id="ef_' + x[0] + '" value="' + esc(e[x[0]] || '') + '"></label>').join('') + '<label class="f">Languages (comma)<input type="text" id="ef_languages" value="' + esc((e.languages || []).join(',')) + '"></label><label class="check"><input type="checkbox" id="ef_ver"' + (e.status === 'verified' ? ' checked' : '') + '><span>Owner confirmed (verified)</span></label><div class="row" style="margin-top:8px"><button class="btn primary" id="efOk">' + esc(t('save')) + '</button><button class="btn ghost" data-close>' + esc(t('cancel')) + '</button></div>', (el2, close) => { $('#efOk', el2).onclick = () => { const g = k => $('#ef_' + k, el2).value.trim(); const n = Object.assign({}, e, { id: e.id || DB.newId('EM'), jurisdiction: g('jurisdiction').toUpperCase(), service: g('service'), label: g('label'), primary: g('primary'), backup: g('backup'), hours: g('hours'), owner: g('owner'), source: g('source'), sourceUrl: g('sourceUrl'), reviewDue: g('reviewDue'), languages: g('languages').split(',').map(x => x.trim()).filter(Boolean) }); if (!n.label || !n.jurisdiction) return; if ($('#ef_ver', el2).checked) { n.status = 'verified'; n.verifiedAt = DB.nowIso(); n.verifiedBy = s.id; } else if (n.status === 'verified') n.status = 'pending'; n.history = (e.history || []).concat([{ at: DB.nowIso(), by: s.id }]); DB.put('emergency', n); DB.audit('emergency:save', n.id); close(); view(); }; });
    $('#eAdd').onclick = () => edit({ status: 'pending', languages: [] });
    $$('[data-eed]').forEach(b => b.onclick = () => edit(DB.get('emergency', b.getAttribute('data-eed'))));
    $$('[data-erev]').forEach(b => b.onclick = () => PRO.reason(t('adm_revalidate') + ' (' + t('adm_evidence') + ')', r => { const e = DB.get('emergency', b.getAttribute('data-erev')); e.status = 'verified'; e.verifiedAt = DB.nowIso(); e.verifiedBy = s.id; e.evidence = r; const d = new Date(); d.setMonth(d.getMonth() + 3); e.reviewDue = d.toISOString().slice(0, 10); DB.put('emergency', e); DB.audit('emergency:revalidate', e.id, { reason: r }); view(); }));
    $$('[data-ehide]').forEach(b => b.onclick = () => PRO.reason(t('adm_hide'), r => { const e = DB.get('emergency', b.getAttribute('data-ehide')); e.status = 'hidden'; e.hiddenReason = r; DB.put('emergency', e); DB.audit('emergency:hide', e.id, { reason: r }); view(); }));
    $('#eCsv').onclick = () => { DB.audit('export:emergency'); UI.download('hwc-emergency.csv', DB.toCSV(em.map(e => Object.assign({}, e, { languages: (e.languages || []).join('|') })), ['id','jurisdiction','service','label','primary','backup','hours','languages','owner','source','sourceUrl','status','verifiedAt','verifiedBy','reviewDue']), 'text/csv'); };
    $('#eImp').onchange = e => importCSV(e.target.files[0], 'emergency', r => ({ id: r.id || DB.newId('EM'), jurisdiction: (r.jurisdiction || '').toUpperCase(), service: r.service, label: r.label, primary: r.primary, backup: r.backup || '', hours: r.hours || '', languages: (r.languages || '').split('|').filter(Boolean), owner: r.owner || '', source: r.source || 'import', sourceUrl: r.sourceUrl || '', status: r.status === 'verified' ? 'verified' : 'pending', verifiedAt: r.verifiedAt || null, verifiedBy: r.verifiedBy || null, reviewDue: r.reviewDue || '' }), x => x.label && x.jurisdiction);
  }

  function content(s, el) {
    const kb = DB.all('kb'); const langs = LANGS.map(l => l.code);
    const cov = code => { const total = Object.keys(T.en).length; const have = Object.keys(T[code] || {}).length; return Math.round(100 * have / total); };
    el.innerHTML = '<h3>' + esc(t('adm_content')) + ' (' + kb.length + ')</h3><p class="hint">Curated, versioned, clinically approved knowledge used by the guide (ToR §10). Items without a translation fall back to English and are labelled.</p><div class="card">' + kb.map(k => '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(k.title.en) + '</span><span class="badge ' + (k.approvedAt ? 'b-green' : 'b-amber') + '">v' + esc(k.version) + '</span></div><div class="meta">' + esc(k.tags.join(', ')) + ' · ' + esc(k.source) + ' · ' + esc(k.approvedBy) + ' ' + esc(k.approvedAt || '') + '</div><div class="pill-row" style="margin-top:4px">' + langs.map(c => '<span class="badge ' + (k.body[c] ? 'b-green' : 'b-grey') + '">' + c.toUpperCase() + '</span>').join('') + '</div><div class="row" style="margin-top:6px"><button class="btn small ghost" data-ked="' + k.id + '">' + esc(t('edit')) + '</button><button class="btn small danger" data-kdel="' + k.id + '">' + esc(t('delete')) + '</button></div></div></div>').join('') + '<button class="btn small" id="kAdd">+ ' + esc(t('adm_add')) + '</button></div>' +
      '<h3>' + esc(t('adm_translations')) + ' · i18n v' + I18N_VERSION + '</h3><div class="card">' + table(langs.map(c => ({ c, name: LANGS.find(l => l.code === c).name, cov: cov(c) + '%', status: c === 'en' ? 'reference' : 'draft, native clinical review pending' })), [['Code','c'],['Language','name'],['Key coverage','cov'],['Status','status']]) + '<p class="hint">Emergency, consent and clinical strings must be approved by professional translators and native health reviewers before pilot (ToR §13). Export keys for review:</p><button class="btn small ghost" id="tExp">⬇ ' + esc(t('adm_export')) + ' i18n CSV</button></div>' +
      '<h3>' + esc(t('red_flag')) + ' rules (' + DB.all('redFlags').length + ')</h3><div class="card">' + table(DB.all('redFlags'), [['ID','id'],['Rule','label'],['Keywords',r => Object.keys(r.kw).map(l => l.toUpperCase() + ': ' + r.kw[l].length).join(' · ')]]) + '<p class="hint">Clinician-approved rules sit before any guide dialogue (ToR §10). Edit via JSON export/import until the rules editor is added.</p></div>';
    const edit = k => UI.modal('<h2>' + esc(t('adm_content')) + '</h2><label class="f">ID<input type="text" id="kf_id" value="' + esc(k.id) + '"' + (k.id ? ' readonly' : '') + '></label><label class="f">Tags (comma)<input type="text" id="kf_tags" value="' + esc(k.tags.join(',')) + '"></label><label class="f">Source<input type="text" id="kf_source" value="' + esc(k.source) + '"></label><label class="f">Version<input type="text" id="kf_version" value="' + esc(k.version) + '"></label>' + langs.map(c => '<label class="f">Title ' + c.toUpperCase() + '<input type="text" id="kf_t_' + c + '" value="' + esc(k.title[c] || '') + '"></label><label class="f">Body ' + c.toUpperCase() + '<textarea id="kf_b_' + c + '">' + esc(k.body[c] || '') + '</textarea></label>').join('') + '<label class="check"><input type="checkbox" id="kf_appr"' + (k.approvedAt ? ' checked' : '') + '><span>Clinically approved</span></label><div class="row" style="margin-top:8px"><button class="btn primary" id="kfOk">' + esc(t('save')) + '</button><button class="btn ghost" data-close>' + esc(t('cancel')) + '</button></div>', (el2, close) => { $('#kfOk', el2).onclick = () => { const g = id => $('#' + id, el2).value.trim(); const n = { id: g('kf_id') || DB.newId('KB'), tags: g('kf_tags').split(',').map(x => x.trim()).filter(Boolean), source: g('kf_source'), version: g('kf_version') || '1.0', title: {}, body: {} }; langs.forEach(c => { if (g('kf_t_' + c)) n.title[c] = g('kf_t_' + c); if (g('kf_b_' + c)) n.body[c] = g('kf_b_' + c); }); if (!n.title.en || !n.body.en) return; n.approvedBy = $('#kf_appr', el2).checked ? s.name : ''; n.approvedAt = $('#kf_appr', el2).checked ? DB.nowIso().slice(0, 10) : null; DB.put('kb', n); DB.audit('kb:save', n.id); close(); view(); }; });
    $('#kAdd').onclick = () => edit({ id: '', tags: [], source: '', version: '1.0', title: {}, body: {} });
    $$('[data-ked]').forEach(b => b.onclick = () => edit(DB.get('kb', b.getAttribute('data-ked'))));
    $$('[data-kdel]').forEach(b => b.onclick = () => UI.confirm(t('delete') + '?', () => { DB.remove('kb', b.getAttribute('data-kdel')); DB.audit('kb:delete', b.getAttribute('data-kdel')); view(); }));
    $('#tExp').onclick = () => UI.download('hwc-i18n.csv', DB.toCSV(Object.keys(T.en).map(k => { const o = { key: k }; langs.forEach(c => o[c] = (T[c] || {})[k] || ''); return o; }), ['key'].concat(langs)), 'text/csv');
  }

  function flags(s, el) {
    const f = DB.all('flags'); const desc = { guide: 'AI guide (navigation, intake, knowledge retrieval)', whatsapp: 'WhatsApp companion links and notifications', telegram: 'Telegram bot / Mini App companion', map: 'Map view (loads OpenStreetMap tiles, needs connection)', wellbeing: 'Wellbeing marketplace', products: "Han's products storefront", pharmacy: 'Pharmacy search and prescription requests', voice: 'Voice notes', ratings: 'Ratings (only with moderation, anti-retaliation and right of reply)', telebirr: 'Telebirr payments (approved payment phase only)' };
    el.innerHTML = '<p class="hint">' + esc(t('adm_kill')) + ': a clinical safety officer or administrator can disable a feature, channel or the guide without deploying code (ToR §12).</p><div class="card">' + Object.keys(desc).map(k => '<label class="check"><input type="checkbox" data-flag="' + k + '"' + (f[k] !== false ? ' checked' : '') + '><span><b>' + esc(k) + '</b> · ' + esc(desc[k]) + '</span></label>').join('') + '</div>';
    $$('[data-flag]').forEach(c => c.onchange = () => { DB.setFlag(c.getAttribute('data-flag'), c.checked); UI.toast(c.getAttribute('data-flag') + ': ' + c.checked); });
  }
  function complaints(s, el) {
    const cs = DB.all('complaints').sort((a, b) => b.at.localeCompare(a.at));
    el.innerHTML = '<p class="hint">Adverse events, wrong-person disclosure, unsafe advice, impersonation, stock misrepresentation, delayed emergency and data-subject requests require root-cause review (ToR §12). Patient data is masked.</p>' + table(cs, [['Date',c => esc(UI.fmtDate(c.at, true))],['Type',c => esc(c.type)],['Case',c => esc(c.caseId || '-')],['Text',c => esc(c.text)],['Contact',c => c.phone ? esc(c.phone.slice(0, 4)) + '•••' + esc(c.phone.slice(-2)) : '-'],['Lang','lang'],['State',c => '<span class="badge ' + (c.state === 'open' ? 'b-amber' : c.state === 'in_review' ? 'b-blue' : 'b-green') + '">' + esc(c.state) + '</span>']], c => c.state === 'closed' ? '' : '<div class="row"><button class="btn small ghost" data-cst="' + c.id + '" data-to="in_review">Review</button><button class="btn small success" data-cst="' + c.id + '" data-to="closed">Close</button></div>');
    $$('[data-cst]').forEach(b => b.onclick = () => PRO.reason(b.getAttribute('data-to'), r => { const c = DB.get('complaints', b.getAttribute('data-cst')); c.state = b.getAttribute('data-to'); c.resolution = (c.resolution || []).concat([{ at: DB.nowIso(), by: s.id, note: r }]); DB.put('complaints', c); DB.audit('complaint:' + c.state, c.id, { reason: r }); view(); }));
  }
  function hans(s, el) {
    const os = DB.all('orders').filter(o => o.seller === 'HANS').sort((a, b) => b.createdAt.localeCompare(a.createdAt)); const ps = DB.all('hansProducts');
    el.innerHTML = '<h3>' + esc(t('pro_orders')) + ' (' + os.length + ')</h3><div class="card">' + (os.length ? os.map(PRO.orderRow).join('') : '<p class="muted">' + esc(t('pro_no_items')) + '</p>') + '</div><h3>' + esc(t('pro_products')) + '</h3><div class="card">' + table(ps, [['Product','name'],['Category','category'],['Variants',p => p.variants.map(v => esc(v.label) + ' ' + v.price).join(', ')],['Stock',p => UI.stockBadge(p.stock)]], p => '<select data-hstock="' + p.id + '" class="in" style="min-height:40px">' + ['available','limited','unavailable','expected'].map(sv => '<option value="' + sv + '"' + (p.stock === sv ? ' selected' : '') + '>' + esc(t('stock_' + sv)) + '</option>').join('') + '</select>') + '<p class="hint">Prices are indicative placeholders; commercial data is separated from clinical records (ToR §6).</p></div>';
    PRO.bindOrders();
    $$('[data-hstock]').forEach(sel => sel.onchange = () => { const p = DB.get('hansProducts', sel.getAttribute('data-hstock')); p.stock = sel.value; DB.put('hansProducts', p); DB.audit('hans:stock', p.id, { result: p.stock }); });
  }
  function fees(s, el) {
    const f = DB.all('fees');
    el.innerHTML = '<p class="hint">' + esc(f.note || '') + '</p><div class="card">' + [['pharmacySubscriptionMonthly','Pharmacy subscription (ETB / month)'],['shopSubscriptionMonthly','Shop subscription (ETB / month)'],['wellbeingPlatformFeePct','Wellbeing platform fee (%)'],['retailPlatformFeePct','Retail platform fee (%)']].map(x => '<label class="f">' + esc(x[1]) + '<input type="number" id="fee_' + x[0] + '" value="' + esc(f[x[0]] || 0) + '"></label>').join('') + '<label class="f">Note<textarea id="fee_note">' + esc(f.note || '') + '</textarea></label><button class="btn primary" id="feeOk">' + esc(t('save')) + '</button><p class="hint">Emergency access, public health information and basic search stay free; fees never influence verification or emergency ranking (ToR §21). Telebirr is a later phase with server-to-server verification, idempotent orders and reconciliation.</p></div>';
    $('#feeOk').onclick = () => { const n = {}; ['pharmacySubscriptionMonthly','shopSubscriptionMonthly','wellbeingPlatformFeePct','retailPlatformFeePct'].forEach(k => n[k] = +$('#fee_' + k).value || 0); n.note = $('#fee_note').value; DB.setObj('fees', n); DB.audit('fees:save'); UI.toast(t('save') + ' ✓'); };
  }
  function audit(s, el) {
    const a = DB.all('audit').slice().reverse().slice(0, 300);
    el.innerHTML = '<p class="hint">Tamper-evident chain (each entry hashes the previous one). Authentication, reads, exports, disclosures, verification and clinical-safety actions are logged (ToR §12).</p><div class="row"><button class="btn small ghost" id="aCsv">⬇ CSV</button><span class="small muted">' + DB.all('audit').length + ' entries · chain ' + (verifyChain() ? '<span class="badge b-green">intact</span>' : '<span class="badge b-red">BROKEN</span>') + '</span></div>' + table(a, [['At',x => esc(UI.fmtDate(x.at, true))],['Actor',x => esc(x.actor) + '<br><small>' + esc(x.role) + '</small>'],['Action','action'],['Object','object'],['Reason / result',x => esc(x.reason || x.result || '')],['Hash',x => '<code class="small">' + esc(x.hash) + '</code>']]);
    $('#aCsv').onclick = () => { DB.audit('export:audit'); UI.download('hwc-audit.csv', DB.toCSV(DB.all('audit'), ['id','at','actor','role','action','object','reason','result','prev','hash']), 'text/csv'); };
  }
  function verifyChain() { const arr = DB.all('audit'); let prev = '0'; for (const e of arr) { if (e.prev !== prev) return false; const h = DB.hash(prev + JSON.stringify([e.at, e.actor, e.action, e.object, e.reason || '', e.result || ''])); if (h !== e.hash) return false; prev = e.hash; } return true; }
  function users(s, el) {
    if (DB.remote && DB.remote.enabled) { const ps = DB.all('profiles'); el.innerHTML = '<p class="hint">Accounts are Supabase Auth users with a profile row (role, name, linked record). Create the user under Authentication → Users, then add the profile here or with supabase/profiles.sql. Production adds MFA and quarterly access review (ToR §5).</p>' + table(ps, [['User','user_id'],['Name','name'],['Role','role'],['Linked',u => esc(u.linked || '-')],['Active',u => u.active === false ? 'no' : 'yes']]) + '<p class="hint">Consents recorded: ' + DB.all('consents').length + '</p>'; return; }
    el.innerHTML = '<p class="hint">Role-based and attribute-based access (ToR §5). Production accounts require MFA, device/session controls and quarterly access review; PINs below are for the demonstration only.</p>' + table(DB.all('users'), [['ID','id'],['Name','name'],['Role','role'],['Linked record',u => esc(u.linked || '-')],['Auth',u => u.pin ? 'PIN' : 'demo (no password)']]) + '<p class="hint">Consents recorded: ' + DB.all('consents').length + ' · Devices with cases: ' + new Set(DB.all('cases').map(c => c.device)).size + '</p>';
  }
  return { view };
})();
