/* Patient and public journeys (ToR §6, §7). One canonical case/order state machine shared with pro.js. */
const CASES = (() => {
  const REQ = { draft: ['queued_offline','submitted','cancelled'], queued_offline: ['submitted','cancelled'], submitted: ['received','cancelled','expired'], received: ['under_review','accepted','clarification_requested','referred','cancelled','expired','closed'], under_review: ['accepted','clarification_requested','referred','closed','cancelled'], clarification_requested: ['under_review','accepted','referred','cancelled','expired','closed'], accepted: ['scheduled','completed','referred','closed','cancelled'], scheduled: ['completed','referred','closed','cancelled'], referred: ['received','completed','closed'], completed: ['closed'], cancelled: ['closed'], expired: ['closed'], closed: [] };
  const ORD = { draft: ['pending_confirmation','cancelled'], pending_confirmation: ['confirmed','cancelled'], confirmed: ['payment_pending','preparing','cancelled'], payment_pending: ['paid','cancelled'], paid: ['preparing','refunded'], preparing: ['ready_for_collection','assigned_for_delivery','cancelled'], ready_for_collection: ['delivered','cancelled'], assigned_for_delivery: ['delivered','disputed'], delivered: ['disputed','refunded'], cancelled: ['refunded'], refunded: [], disputed: ['refunded','delivered'] };
  function can(kind, from, to) { const m = kind === 'order' ? ORD : REQ; return (m[from] || []).includes(to); }
  function transition(obj, to, by, note, kind) {
    kind = kind || (obj.kind === 'order' ? 'order' : 'request');
    if (!can(kind, obj.state, to)) { console.warn('invalid transition', obj.state, '->', to); return false; }
    obj.state = to; obj.timeline = obj.timeline || []; obj.timeline.push({ state: to, at: DB.nowIso(), by: by || 'system', note: note || '' });
    DB.put(kind === 'order' ? 'orders' : 'cases', obj); DB.audit('state:' + to, obj.id, { reason: note || '' });
    return true;
  }
  // Duplicate-safe submission (ToR §7): idempotency key per draft; retries never create a second case.
  function submit(c) {
    const existing = DB.all('cases').find(x => x.idem === c.idem && x.id !== c.id);
    if (existing) return existing;
    if (!navigator.onLine) { if (c.state !== 'queued_offline') transition(c, 'queued_offline', 'patient'); return c; }
    if (c.state === 'draft' || c.state === 'queued_offline') transition(c, 'submitted', 'patient');
    // Demonstration backend acknowledges immediately
    transition(c, 'received', 'system');
    if (c.recipient) DB.notify(c.recipient.id, 'New request ' + c.id, '#/pro/case/' + c.id);
    (c.recipients || []).forEach(r => DB.notify(r, 'New prescription request ' + c.id, '#/pro/case/' + c.id));
    return c;
  }
  function syncQueued() { DB.all('cases').filter(c => c.state === 'queued_offline' && c.device === DB.deviceToken()).forEach(c => submit(c)); }
  window.addEventListener('online', () => { syncQueued(); if (typeof APP !== 'undefined') APP.route(); });
  return { can, transition, submit, syncQueued };
})();

const PATIENT = (() => {
  const { esc, $, $$ } = UI;
  const draft = {}; // in-memory wizard state (never persisted until the user submits or goes offline)

  function langChooser() {
    UI.render('<div class="card"><h1 data-i18n="choose_lang"></h1><div class="lang-grid">' + LANGS.map(l => '<button data-lang="' + l.code + '" aria-pressed="' + (getLang() === l.code) + '" lang="' + l.code + '">' + esc(l.native) + '<br><small class="muted">' + esc(l.name) + '</small></button>').join('') + '</div><p class="hint" style="margin-top:10px">Amharic · Tigrinya · Afaan Oromo · Somali · French · English</p></div>');
    $$('[data-lang]').forEach(b => b.onclick = () => { setLang(b.getAttribute('data-lang')); UI.go('#/'); });
  }

  function home() {
    const s = DB.session();
    UI.render('<h1>' + esc(t('home_title')) + '</h1><p class="muted">' + esc(t('home_sub')) + '</p>' +
      '<div class="tiles">' +
      '<a class="tile em" href="#/emergency"><span class="ic" aria-hidden="true">🚨</span><span>' + esc(t('t_emergency')) + '</span></a>' +
      '<a class="tile" href="#/find?type=practitioner"><span class="ic" aria-hidden="true">🩺</span><span>' + esc(t('t_practitioner')) + '</span></a>' +
      (DB.flag('pharmacy') ? '<a class="tile" href="#/find?type=pharmacy"><span class="ic" aria-hidden="true">💊</span><span>' + esc(t('t_pharmacy')) + '</span></a><a class="tile" href="#/rx"><span class="ic" aria-hidden="true">📄</span><span>' + esc(t('t_prescription')) + '</span></a>' : '') +
      (DB.flag('products') ? '<a class="tile hans" href="#/products"><span class="ic" aria-hidden="true">🌸</span><span>' + esc(t('t_products')) + '</span></a>' : '') +
      (DB.flag('wellbeing') ? '<a class="tile" href="#/find?type=wellbeing"><span class="ic" aria-hidden="true">🧘</span><span>' + esc(t('t_wellbeing')) + '</span></a>' : '') +
      (DB.flag('voice') ? '<a class="tile" href="#/voice"><span class="ic" aria-hidden="true">🎙</span><span>' + esc(t('t_voice')) + '</span></a>' : '') +
      '</div>' +
      '<div class="alert pink small">' + esc(t('home_verified_note')) + '</div>' +
      (s ? '<div class="card"><div class="row between"><b>' + esc(s.name) + '</b><a class="btn small" href="#/pro">' + esc(t('pro_queue')) + '</a></div></div>' : '') +
      '<div id="installBox"></div>' + (DB.remote && DB.remote.enabled ? '' : '<p class="hint">' + esc(t('demo_banner')) + '</p>'));
    APP.installPrompt('installBox');
  }

  // ---------- Emergency (EMR-01..04) ----------
  function emergency() {
    const lang = getLang(); const loc = GEO.saved() || {}; const region = loc.adminUnit ? GEO.regionOf(loc.adminUnit) : null;
    const jur = region ? region.id : null;
    const recs = DB.all('emergency').filter(e => e.status !== 'invalid' && e.status !== 'hidden' && (e.jurisdiction === 'ET' || (jur && e.jurisdiction === jur)));
    const pt = loc.lat != null ? loc : (region ? { lat: region.lat, lng: region.lng } : null);
    const fac = DB.all('facilities').filter(f => f.emergencyCapable && f.verification.state === 'verified').map(f => ({ f, d: pt ? GEO.km(pt, f) : null })).filter(x => x.d === null || x.d < 400).sort((a, b) => (a.d || 9e9) - (b.d || 9e9)).slice(0, 4);
    UI.render('<div class="em-head"><h1>' + esc(t('em_title')) + '</h1><p>' + esc(t('em_sub')) + '</p></div>' +
      '<div class="alert red"><b>' + esc(t('em_redflag_title')) + '</b><p class="small">' + esc(t('em_redflag_body')) + '</p>' + UI.listenBtn(t('em_redflag_body')) + '</div>' +
      '<div class="row between"><b>' + esc(t('em_your_area')) + ' ' + esc(region ? GEO.label(region, lang) : 'Ethiopia') + '</b><button class="linkbtn" id="emArea">' + esc(t('em_change_area')) + '</button></div>' +
      recs.map(e => e.primary ? '<a class="emcall" href="' + UI.telHref(e.primary) + '"><span class="num">' + esc(e.primary) + '</span><span><span class="svc">' + esc(e.label) + '</span><br><small class="muted">' + (e.backup ? esc(t('em_backup')) + ' ' + esc(e.backup) + ' · ' : '') + esc(e.hours) + ' · ' + (e.status === 'verified' ? esc(t('em_verified_on')) + ' ' + esc(UI.fmtDate(e.verifiedAt)) : e.status === 'source-checked' ? esc(t('em_owner_pending')) : esc(t('pending_verif'))) + '</small></span><span class="call">' + esc(t('call')) + '</span></a>' : '').join('') +
      '<div class="card"><div class="row"><button class="btn primary" id="emGps">📍 ' + esc(t('em_share_loc')) + '</button></div><div id="emLoc" class="stack" style="margin-top:8px">' + (loc.adminUnit || loc.lat != null ? locBox(loc) : '') + '</div></div>' +
      '<h2>' + esc(t('em_nearest')) + '</h2>' + (fac.length ? fac.map(x => '<div class="card"><div class="row between"><b>' + esc(x.f.name) + '</b>' + UI.verifBadge(x.f.verification) + '</div><div class="small muted">' + esc(GEO.path(x.f.adminUnit, lang)) + (x.d != null ? ' · ' + x.d.toFixed(1) + ' ' + esc(t('km_away')) : '') + ' · ' + esc(x.f.hours) + '</div><div class="pill-row" style="margin:6px 0">' + x.f.services.map(s => '<span class="badge b-blue">' + esc(s) + '</span>').join('') + '</div><div class="row">' + (x.f.phone ? '<a class="btn call small" href="' + UI.telHref(x.f.phone) + '">📞 ' + esc(t('call')) + '</a>' : '<span class="badge b-amber">' + esc(t('pending_verif')) + ': ' + esc(t('phone')) + '</span>') + '<a class="btn ghost small" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=' + x.f.lat + ',' + x.f.lng + '">🧭 ' + esc(t('directions')) + '</a></div></div>').join('') : '<p class="muted">' + esc(t('no_results')) + '</p>') +
      '<div class="alert amber small">' + esc(t('em_disclaimer')) + '</div>' +
      '<a class="btn ghost block" href="#/request?need=emergency_record">' + esc(t('em_record_incident')) + '</a>', { title: t('em_title') });
    UI.bindListen();
    $('#emArea').onclick = () => pickArea(u => { const l = GEO.saved() || {}; l.adminUnit = u; GEO.save(l); emergency(); });
    $('#emGps').onclick = () => { const box = $('#emLoc'); box.innerHTML = '<p class="muted">' + esc(t('em_sending_loc')) + '…</p>'; GEO.gps().then(p => { const near = GEO.nearestUnit(p, 3); const l = { lat: p.lat, lng: p.lng, acc: p.acc, adminUnit: (near && near.km < 60) ? near.unit.id : (GEO.saved() || {}).adminUnit, landmark: (GEO.saved() || {}).landmark }; GEO.save(l); emergency(); }).catch(() => { box.innerHTML = '<p class="err">' + esc(t('em_gps_denied')) + ' ' + esc(t('em_no_gps')) + '</p>'; }); };
    bindLocBox();
  }
  function locBox(loc) { const s = GEO.summary(loc, getLang()); return '<div class="alert blue"><b>' + esc(t('em_loc_summary')) + '</b><pre class="small" style="white-space:pre-wrap;margin:6px 0">' + esc(s) + '</pre><div class="row"><button class="btn small" id="locCopy">' + esc(t('copy')) + '</button><button class="btn ghost small" id="locShare">' + esc(t('share')) + '</button><a class="btn ghost small" href="sms:?body=' + encodeURIComponent(s) + '">SMS</a></div><p class="hint">' + esc(t('em_copy_hint')) + '</p></div>'; }
  function bindLocBox() { const c = $('#locCopy'), sh = $('#locShare'); if (c) c.onclick = () => UI.copy(GEO.summary(GEO.saved(), getLang())); if (sh) sh.onclick = () => UI.share(GEO.summary(GEO.saved(), getLang())); }
  function pickArea(cb, initial) {
    UI.modal('<h2>' + esc(t('choose_area')) + '</h2>' + UI.areaPicker('apick', initial || (GEO.saved() || {}).adminUnit, v => { sel = v; }) + '<label class="f">' + esc(t('landmark')) + '<input type="text" id="apLand" value="' + esc((GEO.saved() || {}).landmark || '') + '"></label><div class="row" style="margin-top:10px"><button class="btn primary" id="apOk">' + esc(t('ok')) + '</button><button class="btn ghost" data-close>' + esc(t('cancel')) + '</button></div>', (el, close) => { $('#apOk', el).onclick = () => { const l = GEO.saved() || {}; l.landmark = $('#apLand', el).value.trim(); GEO.save(l); close(); cb(sel); }; });
    let sel = initial || (GEO.saved() || {}).adminUnit || null;
  }

  // ---------- Find (PAT-03) ----------
  const F = { type: 'practitioner', q: '', area: null, spec: '', lang: '', gender: '', mode: '', avail: '', view: 'list', pt: null };
  function find() {
    const q = UI.qs(); if (q.type) F.type = q.type; if (q.spec) F.spec = q.spec;
    if (!F.area && GEO.saved() && GEO.saved().adminUnit) F.area = GEO.saved().adminUnit;
    if (!F.pt && GEO.saved() && GEO.saved().lat != null) F.pt = GEO.saved();
    const lang = getLang();
    const items = results();
    const typeTabs = [['practitioner','find_type_practitioner'],['pharmacy','find_type_pharmacy'],['facility','find_type_facility']].concat(DB.flag('wellbeing') ? [['wellbeing','find_type_wellbeing']] : []);
    UI.render('<h1>' + esc(t('find_title')) + '</h1>' +
      '<div class="tabs" role="tablist">' + typeTabs.map(x => '<button role="tab" data-type="' + x[0] + '" aria-selected="' + (F.type === x[0]) + '">' + esc(t(x[1])) + '</button>').join('') + '</div>' +
      '<div class="card flat"><div class="row"><input type="search" id="fq" class="in" style="flex:1;min-width:160px" placeholder="' + esc(t('search')) + ' · ' + esc(t('kebele_landmark')) + '" value="' + esc(F.q) + '"><button class="btn ghost small" id="fGps">📍 ' + esc(t('use_gps')) + '</button><button class="btn ghost small" id="fArea">🗺 ' + esc(t('choose_area')) + '</button></div>' +
      '<div class="small muted" style="margin:6px 0">' + (F.area ? esc(GEO.path(F.area, lang)) : esc(t('any_area'))) + (F.pt ? ' · GPS' : '') + '</div>' +
      '<details><summary class="btn ghost small" style="display:inline-flex">' + esc(t('filter')) + '</summary><div class="grid2" style="margin-top:8px">' +
      (F.type === 'practitioner' ? '<label class="f">' + esc(t('specialty')) + '<select id="fSpec"><option value="">' + esc(t('all')) + '</option>' + ['general','maternal','child','chronic','mental','srh','medication'].map(s => '<option value="' + s + '"' + (F.spec === s ? ' selected' : '') + '>' + esc(t('need_' + s)) + '</option>').join('') + '</select></label>' : '') +
      '<label class="f">' + esc(t('language')) + '<select id="fLang"><option value="">' + esc(t('all')) + '</option>' + LANGS.map(l => '<option value="' + l.code + '"' + (F.lang === l.code ? ' selected' : '') + '>' + esc(l.native) + '</option>').join('') + '</select></label>' +
      (F.type !== 'facility' && F.type !== 'pharmacy' ? '<label class="f">' + esc(t('gender')) + '<select id="fGender"><option value="">' + esc(t('gender_any')) + '</option><option value="f"' + (F.gender === 'f' ? ' selected' : '') + '>' + esc(t('gender_f')) + '</option><option value="m"' + (F.gender === 'm' ? ' selected' : '') + '>' + esc(t('gender_m')) + '</option></select></label>' : '') +
      (F.type === 'practitioner' ? '<label class="f">' + esc(t('service_mode')) + '<select id="fMode"><option value="">' + esc(t('all')) + '</option>' + ['home_visit','phone_audio','secure_chat','by_appointment','video'].map(m => '<option value="' + m + '"' + (F.mode === m ? ' selected' : '') + '>' + esc(t(m)) + '</option>').join('') + '</select></label><label class="f">' + esc(t('availability')) + '<select id="fAvail"><option value="">' + esc(t('all')) + '</option><option value="available_now"' + (F.avail === 'available_now' ? ' selected' : '') + '>' + esc(t('available_now')) + '</option><option value="by_appointment"' + (F.avail === 'by_appointment' ? ' selected' : '') + '>' + esc(t('by_appointment')) + '</option></select></label>' : '') +
      '</div><button class="linkbtn" id="fClear">' + esc(t('clear_filters')) + '</button></details></div>' +
      '<div class="row between"><b>' + items.length + ' ' + esc(t('results')) + '</b>' + (DB.flag('map') ? '<div class="tabs" style="margin:0"><button data-view="list" aria-selected="' + (F.view === 'list') + '">' + esc(t('list_view')) + '</button><button data-view="map" aria-selected="' + (F.view === 'map') + '">' + esc(t('map_view')) + '</button></div>' : '') + '</div>' +
      (F.view === 'map' ? '<div id="map"><p class="muted small" style="padding:10px">' + esc(t('map_loading')) + '</p></div>' : '') +
      (items.length ? '<div class="card">' + items.map(card).join('') + '</div><p class="hint">' + esc(t('distance_approx')) + '</p>' : '<div class="alert amber">' + esc(t('no_results')) + '</div><a class="btn danger block" href="#/emergency">' + esc(t('t_emergency')) + '</a>'), { title: t('find_title') });
    $$('[data-type]').forEach(b => b.onclick = () => { F.type = b.getAttribute('data-type'); find(); });
    $$('[data-view]').forEach(b => b.onclick = () => { F.view = b.getAttribute('data-view'); find(); });
    $('#fq').oninput = e => { F.q = e.target.value; refreshList(); };
    $('#fGps').onclick = () => GEO.gps().then(p => { F.pt = p; const near = GEO.nearestUnit(p, 3); if (near && near.km < 60) F.area = near.unit.id; GEO.save(Object.assign(GEO.saved() || {}, { lat: p.lat, lng: p.lng, acc: p.acc, adminUnit: F.area })); find(); }).catch(() => UI.toast(t('em_gps_denied')));
    $('#fArea').onclick = () => pickArea(u => { F.area = u; const l = GEO.saved() || {}; l.adminUnit = u; GEO.save(l); find(); }, F.area);
    ['fSpec','fLang','fGender','fMode','fAvail'].forEach(id => { const el = $('#' + id); if (el) el.onchange = () => { F[{ fSpec: 'spec', fLang: 'lang', fGender: 'gender', fMode: 'mode', fAvail: 'avail' }[id]] = el.value; find(); }; });
    $('#fClear').onclick = () => { F.q = ''; F.spec = ''; F.lang = ''; F.gender = ''; F.mode = ''; F.avail = ''; F.area = null; F.pt = null; find(); };
    if (F.view === 'map') loadMap(items);
  }
  function refreshList() { const items = results(); const c = $('.main .card:last-of-type'); if (c && c.querySelector('.item')) c.innerHTML = items.map(card).join(''); }
  function results() {
    const lang = getLang(); const q = F.q.trim().toLowerCase();
    let src;
    if (F.type === 'practitioner') src = DB.all('practitioners').map(p => ({ kind: 'practitioner', o: p, name: p.name, sub: p.specialty, unit: p.adminUnit, pt: p, langs: p.languages, gender: p.gender, verif: p.verification, avail: p.availability, modes: p.modes, scope: p.scope }));
    else if (F.type === 'pharmacy') src = DB.all('facilities').filter(f => f.type === 'pharmacy').map(f => ({ kind: 'pharmacy', o: f, name: f.name, sub: f.hours, unit: f.adminUnit, pt: f, langs: f.languages, verif: f.verification }));
    else if (F.type === 'facility') src = DB.all('facilities').filter(f => f.type !== 'pharmacy').map(f => ({ kind: 'facility', o: f, name: f.name, sub: f.type + ' · ' + f.hours, unit: f.adminUnit, pt: f, langs: f.languages, verif: f.verification }));
    else src = DB.all('wellbeing').map(w => ({ kind: 'wellbeing', o: w, name: w.name, sub: w.service + ' · ' + w.price, unit: w.adminUnit, pt: w, langs: w.languages, gender: w.gender, verif: w.verification, avail: w.availability }));
    // Verification before visibility (ToR §3): unverified records are listed only as "pending" and cannot be requested.
    src = src.filter(x => x.verif.state === 'verified' || x.verif.state === 'pending');
    if (F.area) src = src.filter(x => GEO.isWithin(x.unit, F.area) || (F.pt && GEO.km(F.pt, x.pt) < 25));
    if (F.lang) src = src.filter(x => (x.langs || []).includes(F.lang));
    if (F.gender) src = src.filter(x => !x.gender || x.gender === F.gender);
    if (F.spec && F.type === 'practitioner') src = src.filter(x => (x.scope || []).includes(F.spec));
    if (F.mode) src = src.filter(x => (x.modes || []).includes(F.mode));
    if (F.avail) src = src.filter(x => x.avail === F.avail);
    if (q) src = src.filter(x => (x.name + ' ' + x.sub + ' ' + GEO.path(x.unit, lang) + ' ' + (GEO.unit(x.unit) || {}).local + ' ' + ((GEO.unit(x.unit) || {}).aliases || []).join(' ')).toLowerCase().includes(q));
    src.forEach(x => x.d = F.pt ? GEO.km(F.pt, x.pt) : null);
    // Ranking: verified first, then availability, then distance. Never paid placement (ToR §21).
    src.sort((a, b) => (a.verif.state === 'verified' ? 0 : 1) - (b.verif.state === 'verified' ? 0 : 1) || (a.avail === 'available_now' ? 0 : 1) - (b.avail === 'available_now' ? 0 : 1) || ((a.d == null ? 9e9 : a.d) - (b.d == null ? 9e9 : b.d)) || a.name.localeCompare(b.name));
    return src;
  }
  function card(x) {
    const lang = getLang(); const v = x.verif.state === 'verified';
    return '<div class="item"><div class="avatar" aria-hidden="true">' + esc(x.name.replace(/^(Dr\.|Sr\.|Ph\.|Nurse)\s*/, '')[0] || '?') + '</div><div class="body"><div class="row between"><span class="title">' + esc(x.name) + '</span>' + UI.verifBadge(x.verif) + '</div><div class="meta">' + esc(x.sub) + '</div><div class="meta">' + esc(GEO.path(x.unit, lang)) + (x.d != null ? ' · ' + x.d.toFixed(1) + ' ' + esc(t('km_away')) : '') + '</div><div class="pill-row" style="margin:6px 0">' + (x.avail ? '<span class="badge ' + (x.avail === 'available_now' ? 'b-green' : x.avail === 'on_leave' || x.avail === 'offline_mode' ? 'b-grey' : 'b-blue') + '">' + esc(t(x.avail)) + '</span>' : '') + '<span class="badge b-grey">' + esc(UI.langNames(x.langs)) + '</span>' + (x.kind === 'wellbeing' ? '<span class="badge b-pink">' + esc(t('wel_label')) + '</span>' : '') + '</div><div class="row"><a class="btn small ghost" href="#/p/' + x.kind + '/' + x.o.id + '">' + esc(t('view_profile')) + '</a>' + (x.o.phone && v ? '<a class="btn small call" href="' + UI.telHref(x.o.phone) + '">📞 ' + esc(t('call')) + '</a>' : '') + '</div></div></div>';
  }
  function loadMap(items) {
    const ensure = () => new Promise((res, rej) => { if (window.L) return res(); const css = document.createElement('link'); css.rel = 'stylesheet'; css.href = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'; document.head.appendChild(css); const s = document.createElement('script'); s.src = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'; s.onload = res; s.onerror = rej; document.head.appendChild(s); });
    if (!navigator.onLine) { $('#map').innerHTML = '<p class="muted small" style="padding:10px">' + esc(t('offline')) + ': ' + esc(t('map_loading')) + '</p>'; return; }
    ensure().then(() => { const el = $('#map'); if (!el) return; el.innerHTML = ''; const c = F.pt || (F.area && GEO.unit(F.area)) || { lat: 9.03, lng: 38.74 }; const m = L.map(el).setView([c.lat, c.lng], F.area ? 12 : 6); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '© OpenStreetMap' }).addTo(m); items.forEach(x => { if (x.pt.lat == null) return; L.marker([x.pt.lat, x.pt.lng]).addTo(m).bindPopup('<b>' + esc(x.name) + '</b><br>' + esc(x.sub) + '<br><a href="#/p/' + x.kind + '/' + x.o.id + '">' + esc(t('view_profile')) + '</a>'); }); if (F.pt) L.circleMarker([F.pt.lat, F.pt.lng], { radius: 8, color: '#1E5AA8' }).addTo(m); }).catch(() => { const el = $('#map'); if (el) el.innerHTML = '<p class="muted small" style="padding:10px">' + esc(t('map_loading')) + '</p>'; });
  }

  // ---------- Profiles ----------
  function profile(kind, id) {
    const lang = getLang();
    if (kind === 'practitioner') {
      const p = DB.get('practitioners', id); if (!p) return UI.go('#/find');
      const fac = p.facility ? DB.get('facilities', p.facility) : null; const v = p.verification.state === 'verified'; const exp = UI.daysUntil(p.licence.expiry);
      UI.render('<div class="card"><div class="row between"><h1 style="margin:0">' + esc(p.name) + '</h1>' + UI.verifBadge(p.verification) + '</div><p><b>' + esc(p.specialty) + '</b> · ' + esc(t('role_' + (p.profession === 'midwife' ? 'nurse' : p.profession))) + '</p><p>' + esc(p.bio) + '</p>' +
        '<table class="tbl"><tr><th>' + esc(t('scope')) + '</th><td>' + p.scope.map(s => esc(t('need_' + s))).join(', ') + '</td></tr><tr><th>' + esc(t('languages')) + '</th><td>' + esc(UI.langNames(p.languages)) + '</td></tr><tr><th>' + esc(t('service_mode')) + '</th><td>' + p.modes.map(m => esc(t(m))).join(', ') + '</td></tr><tr><th>' + esc(t('availability')) + '</th><td>' + esc(t(p.availability)) + '</td></tr><tr><th>' + esc(t('service_area')) + '</th><td>' + esc(p.serviceArea) + '<br><small class="muted">' + esc(GEO.path(p.adminUnit, lang)) + '</small></td></tr>' + (fac ? '<tr><th>Facility</th><td><a href="#/p/facility/' + fac.id + '">' + esc(fac.name) + '</a></td></tr>' : '') + '<tr><th>' + esc(t('licence')) + '</th><td>' + esc(p.licence.no) + ' · ' + esc(p.licence.issuer) + ' · ' + esc(t('expires')) + ' ' + esc(p.licence.expiry || '-') + (exp !== null && exp < 60 ? ' <span class="badge b-amber">' + esc(t('pro_expiring')) + '</span>' : '') + '</td></tr><tr><th>' + esc(t('last_verified')) + '</th><td>' + esc(UI.fmtDate(p.verification.verifiedAt)) + '</td></tr></table></div>' +
        (v && p.availability !== 'on_leave' && p.availability !== 'offline_mode' ? '<div class="row"><a class="btn primary" href="#/request?to=' + p.id + '">' + esc(t('request_now')) + '</a><a class="btn ghost" href="#/request?to=' + p.id + '&appt=1">' + esc(t('request_appt')) + '</a><a class="btn ghost" href="#/voice?to=' + p.id + '">🎙 ' + esc(t('t_voice')) + '</a></div>' : '<div class="alert amber">' + esc(v ? t(p.availability) : t('pending_verif')) + '</div>'), { back: true, title: p.name });
    } else if (kind === 'pharmacy' || kind === 'facility') {
      const f = DB.get('facilities', id); if (!f) return UI.go('#/find');
      const prods = kind === 'pharmacy' ? DB.all('pharmacyProducts').filter(x => x.pharmacy === f.id) : [];
      const stale = ts => (Date.now() - new Date(ts)) > 72 * 3600e3;
      UI.render('<div class="card"><div class="row between"><h1 style="margin:0">' + esc(f.name) + '</h1>' + UI.verifBadge(f.verification) + '</div><p class="muted">' + esc(GEO.path(f.adminUnit, lang)) + '</p><table class="tbl"><tr><th>' + esc(t('em_hours')) + '</th><td>' + esc(f.hours) + '</td></tr><tr><th>' + esc(t('services')) + '</th><td>' + f.services.map(s => esc(s)).join(', ') + '</td></tr><tr><th>' + esc(t('languages')) + '</th><td>' + esc(UI.langNames(f.languages)) + '</td></tr>' + (f.responsiblePharmacist ? '<tr><th>' + esc(t('role_pharmacist')) + '</th><td>' + esc(f.responsiblePharmacist) + '</td></tr>' : '') + (f.licence && f.licence.no ? '<tr><th>' + esc(t('licence')) + '</th><td>' + esc(f.licence.no) + ' · ' + esc(t('expires')) + ' ' + esc(f.licence.expiry) + '</td></tr>' : '') + (f.delivery ? '<tr><th>' + esc(t('deliver')) + '</th><td>≤ ' + f.deliveryRadiusKm + ' km</td></tr>' : '') + '<tr><th>' + esc(t('last_verified')) + '</th><td>' + esc(UI.fmtDate(f.verification.verifiedAt) || '-') + (f.coordsValidated ? '' : ' · <span class="muted">' + esc(t('distance_approx')) + '</span>') + '</td></tr></table>' +
        '<div class="row" style="margin-top:8px">' + (f.phone ? '<a class="btn call" href="' + UI.telHref(f.phone) + '">📞 ' + esc(t('call')) + '</a>' : '') + '<a class="btn ghost" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=' + f.lat + ',' + f.lng + '">🧭 ' + esc(t('directions')) + '</a>' + (kind === 'pharmacy' && f.verification.state === 'verified' ? '<a class="btn primary" href="#/rx?to=' + f.id + '">📄 ' + esc(t('t_prescription')) + '</a>' : '') + '</div></div>' +
        (prods.length ? '<h2>' + esc(t('pro_stock')) + '</h2><div class="card"><input type="search" class="in" id="pq" placeholder="' + esc(t('search')) + '"><div id="plist">' + prods.map(p => prodRow(p, stale(p.updatedAt))).join('') + '</div><p class="hint">' + esc(t('rx_note_valid')) + '</p></div>' : ''), { back: true, title: f.name });
      const pq = $('#pq'); if (pq) pq.oninput = () => { const q = pq.value.toLowerCase(); $('#plist').innerHTML = prods.filter(p => (p.generic + ' ' + p.brand + ' ' + p.category).toLowerCase().includes(q)).map(p => prodRow(p, stale(p.updatedAt))).join(''); };
    } else if (kind === 'wellbeing') {
      const w = DB.get('wellbeing', id); if (!w) return UI.go('#/find?type=wellbeing');
      UI.render('<div class="alert pink small">' + esc(t('wel_note')) + '</div><div class="card"><div class="row between"><h1 style="margin:0">' + esc(w.name) + '</h1>' + UI.verifBadge(w.verification) + '</div><p><b>' + esc(w.service) + '</b> <span class="badge b-pink">' + esc(t('wel_label')) + '</span></p><table class="tbl"><tr><th>' + esc(t('wel_price')) + '</th><td>' + esc(w.price) + '</td></tr><tr><th>' + esc(t('languages')) + '</th><td>' + esc(UI.langNames(w.languages)) + '</td></tr><tr><th>' + esc(t('gender')) + '</th><td>' + esc(t(w.gender === 'f' ? 'gender_f' : 'gender_m')) + '</td></tr><tr><th>' + esc(t('service_area')) + '</th><td>' + esc(w.serviceArea) + '</td></tr><tr><th>' + esc(t('availability')) + '</th><td>' + esc(t(w.availability)) + '</td></tr><tr><th>' + esc(t('wel_safeguards')) + '</th><td>' + esc(w.safeguards) + '</td></tr><tr><th>' + esc(t('wel_cancel_terms')) + '</th><td>' + esc(w.cancelTerms) + '</td></tr></table></div>' + (w.verification.state === 'verified' ? '<a class="btn primary block" href="#/book/' + w.id + '">' + esc(t('wel_book')) + '</a>' : '<div class="alert amber">' + esc(t('pending_verif')) + '</div>'), { back: true, title: w.name });
    }
  }
  function prodRow(p, stale) { return '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(p.generic) + (p.brand ? ' (' + esc(p.brand) + ')' : '') + '</span>' + (stale && p.stock !== 'not_stocked' ? '<span class="badge b-amber">' + esc(t('stock_confirm')) + '</span>' : UI.stockBadge(p.stock)) + '</div><div class="meta">' + esc([p.strength, p.form, p.pack ? 'x' + p.pack : ''].filter(Boolean).join(' · ')) + ' · <span class="badge ' + (p.rx === 'pom' ? 'b-red' : 'b-grey') + '">' + (p.rx === 'pom' ? 'Rx' : p.rx === 'otc' ? 'OTC' : 'Retail') + '</span>' + (p.price ? ' · ' + p.price + ' ETB' : '') + '</div><div class="meta">' + esc(t('pro_updated')) + ' ' + esc(UI.ago(p.updatedAt)) + (p.expectedDate ? ' · ' + esc(t('stock_expected')) + ' ' + esc(p.expectedDate) : '') + '</div></div></div>'; }

  // ---------- Request wizard (PAT-04/05, workflow "Find a practitioner", "Voice request") ----------
  function request() {
    const q = UI.qs(); const lang = getLang();
    if (!draft.req || draft.req.to !== (q.to || null) || q.reset) { draft.req = { step: 0, to: q.to || null, appt: !!q.appt, need: q.need === 'emergency_record' ? 'emergency_record' : '', urgency: '', text: q.summary ? GUIDE.summarize(chat) : '', files: [], share: { location: 'exact', name: true }, loc: Object.assign({}, GEO.saved() || {}), phone: '', name: '', consent: false, notice: false, otp: false, voiceFirst: !!q.voice }; if (q.reset || q.summary) history.replaceState(null, '', location.hash.replace(/[?&](reset|summary)=1/g, '').replace(/#\/request&/, '#/request?')); }
    const d = draft.req; const to = d.to ? DB.get('practitioners', d.to) : null;
    const steps = ['need','describe','location','contact','review'];
    const head = '<h1>' + esc(t('req_title')) + '</h1>' + (to ? '<p class="muted">' + esc(t('case_with')) + ' <b>' + esc(to.name) + '</b> · ' + esc(to.specialty) + '</p>' : '<p class="muted">' + esc(t('responder_auto')) + '</p>') + '<div class="tabs" aria-hidden="true">' + steps.map((s, i) => '<button tabindex="-1" aria-selected="' + (i === d.step) + '">' + (i + 1) + '</button>').join('') + '</div>';
    let body = '';
    if (d.step === 0) body = '<div class="card"><h2>' + esc(t('req_need')) + '</h2><div class="choices">' + ['general','maternal','child','chronic','mental','srh','medication','other'].map(n => '<button class="choice" data-need="' + n + '" aria-pressed="' + (d.need === n) + '">' + esc(t('need_' + n)) + '</button>').join('') + '</div><h2 style="margin-top:14px">' + esc(t('req_urgency')) + '</h2><div class="choices"><button class="choice" data-urg="routine" aria-pressed="' + (d.urgency === 'routine') + '">' + esc(t('urg_routine')) + '</button><button class="choice" data-urg="soon" aria-pressed="' + (d.urgency === 'soon') + '">' + esc(t('urg_soon')) + '</button><button class="choice" data-urg="urgent" aria-pressed="' + (d.urgency === 'urgent') + '">' + esc(t('urg_urgent')) + '</button></div><div class="alert red small" style="margin-top:12px">' + esc(t('em_redflag_body')) + ' <a href="#/emergency"><b>' + esc(t('t_emergency')) + '</b></a></div></div>';
    if (d.step === 1) body = '<div class="card"><h2>' + esc(t('req_describe')) + '</h2><textarea id="rText" placeholder="' + esc(t('req_describe')) + '">' + esc(d.text) + '</textarea><div id="rfBox"></div><h3>' + esc(t('req_voice')) + '</h3><p class="hint">' + esc(t('voice_privacy')) + '</p><div id="recBox"></div><h3>' + esc(t('req_photo')) + ' / ' + esc(t('req_doc')) + '</h3><input type="file" id="rFile" accept="image/*,application/pdf" capture="environment"><p class="hint">' + esc(t('attach_hint')) + '</p><div id="fileList">' + fileList(d) + '</div></div>';
    if (d.step === 2) body = '<div class="card"><h2>' + esc(t('location_title')) + '</h2><div class="row"><button class="btn ghost" id="rGps">📍 ' + esc(t('location_gps')) + '</button><button class="btn ghost" id="rArea">🗺 ' + esc(t('location_manual')) + '</button></div><p id="rLoc" class="small" style="margin-top:8px">' + esc(d.loc.adminUnit ? GEO.path(d.loc.adminUnit, lang) : t('any_area')) + (d.loc.lat != null ? ' · GPS ✓' : '') + '</p><label class="f">' + esc(t('landmark')) + '<input type="text" id="rLand" value="' + esc(d.loc.landmark || '') + '"></label><h3>' + esc(t('share_choice')) + '</h3><div class="choices"><button class="choice" data-share="exact" aria-pressed="' + (d.share.location === 'exact') + '">' + esc(t('share_location_exact')) + '</button><button class="choice" data-share="area" aria-pressed="' + (d.share.location === 'area') + '">' + esc(t('share_location_area')) + '</button></div></div>';
    if (d.step === 3) body = '<div class="card"><h2>' + esc(t('req_contact')) + '</h2><label class="f">' + esc(t('phone')) + ' <span class="muted">(' + esc(t('required')) + ')</span><input type="tel" id="rPhone" inputmode="tel" placeholder="09.. / +251" value="' + esc(d.phone) + '"></label><p class="hint">' + esc(t('phone_hint')) + '</p><label class="f">' + esc(t('name_optional')) + '<input type="text" id="rName" value="' + esc(d.name) + '"></label><h3>' + esc(t('consent_title')) + '</h3><p class="small">' + esc(t('consent_body')) + '</p><label class="check"><input type="checkbox" id="rConsent"' + (d.consent ? ' checked' : '') + '><span>' + esc(t('consent_share')) + '</span></label><label class="check"><input type="checkbox" id="rNotice"' + (d.notice ? ' checked' : '') + '><span>' + esc(t('consent_agree')) + ' <a href="#/privacy" target="_blank">' + esc(t('menu_privacy')) + '</a></span></label></div>';
    if (d.step === 4) body = '<div class="card"><h2>' + esc(t('review_title')) + '</h2><table class="tbl"><tr><th>' + esc(t('req_need')) + '</th><td>' + esc(t('need_' + (d.need || 'other'))) + ' · ' + esc(t('urg_' + (d.urgency || 'routine'))) + '</td></tr><tr><th>' + esc(t('req_describe')) + '</th><td>' + esc(d.text || '-') + '</td></tr><tr><th>' + esc(t('case_attachments')) + '</th><td>' + (d.files.length ? d.files.map(f => esc(f.kind) + ' (' + UI.fmtBytes(f.size) + ')').join(', ') : '-') + '</td></tr><tr><th>' + esc(t('location_title')) + '</th><td>' + esc(d.loc.adminUnit ? GEO.path(d.loc.adminUnit, lang) : '-') + (d.share.location === 'exact' && d.loc.lat != null ? ' · GPS' : '') + (d.loc.landmark ? ' · ' + esc(d.loc.landmark) : '') + '</td></tr><tr><th>' + esc(t('phone')) + '</th><td>' + esc(d.phone) + (d.otp ? ' ✓' : '') + '</td></tr><tr><th>' + esc(t('case_with')) + '</th><td>' + esc(to ? to.name : t('responder_auto')) + '</td></tr><tr><th>' + esc(t('case_lang')) + '</th><td>' + esc(lang.toUpperCase()) + '</td></tr></table>' + (!navigator.onLine ? '<div class="alert amber"><b>' + esc(t('offline')) + '.</b> ' + esc(t('queued_hint')) + '</div>' : '') + '</div>';
    UI.render(head + body + '<div class="row" style="margin-top:10px">' + (d.step > 0 ? '<button class="btn ghost" id="rPrev">' + esc(t('back')) + '</button>' : '') + (d.step < 4 ? '<button class="btn primary" id="rNext">' + esc(t('next')) + '</button>' : '<button class="btn primary" id="rSend">' + esc(t('submit_request')) + '</button>') + '</div><p class="err" id="rErr"></p>', { back: true, title: t('req_title') });
    const err = m => { $('#rErr').textContent = m; };
    $$('[data-need]').forEach(b => b.onclick = () => { d.need = b.getAttribute('data-need'); $$('[data-need]').forEach(x => x.setAttribute('aria-pressed', x === b)); });
    $$('[data-urg]').forEach(b => b.onclick = () => { d.urgency = b.getAttribute('data-urg'); $$('[data-urg]').forEach(x => x.setAttribute('aria-pressed', x === b)); });
    $$('[data-share]').forEach(b => b.onclick = () => { d.share.location = b.getAttribute('data-share'); $$('[data-share]').forEach(x => x.setAttribute('aria-pressed', x === b)); });
    if (d.step === 1) {
      const ta = $('#rText'); ta.oninput = () => { d.text = ta.value; const rf = GUIDE.redFlag(d.text); $('#rfBox').innerHTML = rf ? '<div class="alert red"><b>' + esc(t('red_flag')) + ': ' + esc(rf.label) + '.</b> ' + esc(t('guide_redflag')) + ' <a class="btn danger small" href="#/emergency">' + esc(t('t_emergency')) + '</a></div>' : ''; };
      UI.recorder('recBox', r => { d.files = d.files.filter(f => f.kind !== 'voice'); if (r) d.files.push(Object.assign({ kind: 'voice' }, r)); $('#fileList').innerHTML = fileList(d); });
      $('#rFile').onchange = e => UI.readFile(e.target.files[0], 2 * 1048576).then(r => { d.files.push(Object.assign({ kind: r.type === 'application/pdf' ? 'doc' : 'photo' }, r)); $('#fileList').innerHTML = fileList(d); bindRemove(d); }).catch(er => err(er.message === 'size' ? t('too_large') : t('retry')));
      bindRemove(d);
    }
    if (d.step === 2) { $('#rGps').onclick = () => GEO.gps().then(p => { const near = GEO.nearestUnit(p, 3); d.loc = Object.assign(d.loc, { lat: p.lat, lng: p.lng, acc: p.acc, adminUnit: near && near.km < 60 ? near.unit.id : d.loc.adminUnit }); GEO.save(d.loc); request(); }).catch(() => err(t('em_gps_denied'))); $('#rArea').onclick = () => pickArea(u => { d.loc.adminUnit = u; d.loc.landmark = (GEO.saved() || {}).landmark; GEO.save(d.loc); request(); }, d.loc.adminUnit); $('#rLand').oninput = e => { d.loc.landmark = e.target.value; }; }
    if (d.step === 3) { $('#rPhone').oninput = e => d.phone = e.target.value; $('#rName').oninput = e => d.name = e.target.value; $('#rConsent').onchange = e => d.consent = e.target.checked; $('#rNotice').onchange = e => d.notice = e.target.checked; }
    const prev = $('#rPrev'); if (prev) prev.onclick = () => { d.step--; request(); };
    const next = $('#rNext'); if (next) next.onclick = () => {
      if (d.step === 0 && (!d.need || !d.urgency)) return err(t('required'));
      if (d.step === 1 && !d.text.trim() && !d.files.length) return err(t('required'));
      if (d.step === 3) { if (!/^(\+?251|0)?9\d{8}$|^\+?\d{9,13}$/.test(d.phone.replace(/\s/g, ''))) return err(t('phone') + ': ' + t('required')); if (!d.consent || !d.notice) return err(t('consent_title') + ': ' + t('required')); if (!d.otp) return otp(() => { d.otp = true; d.step++; request(); }); }
      d.step++; request();
    };
    const send = $('#rSend'); if (send) send.onclick = () => submitRequest(d, to);
  }
  function fileList(d) { return d.files.map((f, i) => '<div class="row between small"><span>' + esc(f.kind) + ' · ' + esc(f.name || '') + ' · ' + UI.fmtBytes(f.size) + '</span><button class="linkbtn" data-rm="' + i + '">' + esc(t('remove')) + '</button></div>').join(''); }
  function bindRemove(d) { $$('[data-rm]').forEach(b => b.onclick = () => { d.files.splice(+b.getAttribute('data-rm'), 1); $('#fileList').innerHTML = fileList(d); bindRemove(d); }); }
  function otp(cb) {
    UI.modal('<h2>' + esc(t('otp_title')) + '</h2><p class="small">' + esc(t('otp_hint')) + '</p><label class="f">' + esc(t('otp_code')) + '<input type="text" inputmode="numeric" maxlength="4" id="otpIn" autocomplete="one-time-code"></label><div class="row"><button class="btn primary" id="otpOk">' + esc(t('verify')) + '</button><button class="btn ghost" data-close>' + esc(t('cancel')) + '</button></div>', (el, close) => { $('#otpOk', el).onclick = () => { if (/^\d{4}$/.test($('#otpIn', el).value)) { close(); cb(); } }; });
  }
  async function submitRequest(d, to) {
    const id = DB.newId('RQ'); const atts = [];
    for (const f of d.files) { const fid = DB.newId('AT'); try { await DB.files.put(fid, f.blob, { case: id, kind: f.kind, type: f.type, path: id + '/' + fid }); atts.push({ id: fid, kind: f.kind, name: f.name || f.kind, size: f.size, type: f.type, secs: f.secs || null, path: id + '/' + fid }); } catch (e) { console.warn('file store failed', e); } }
    const consent = DB.put('consents', { id: DB.newId('CS'), subject: DB.deviceToken(), phoneHash: DB.hash(d.phone), purpose: 'health-request', recipient: to ? to.id : 'auto', lang: getLang(), version: I18N_VERSION, at: DB.nowIso(), withdrawnAt: null });
    let recipient = to ? { kind: 'practitioner', id: to.id, name: to.name } : autoMatch(d);
    const c = { id, kind: 'request', type: d.voiceFirst ? 'voice' : d.need === 'emergency_record' ? 'emergency_record' : 'health', idem: DB.newId('IDM'), device: DB.deviceToken(), phone: d.phone, name: d.share.name ? d.name : '', lang: getLang(), need: d.need, urgency: d.urgency, appt: d.appt, text: d.text, attachments: atts, location: { adminUnit: d.loc.adminUnit || null, lat: d.share.location === 'exact' ? d.loc.lat : null, lng: d.share.location === 'exact' ? d.loc.lng : null, landmark: d.loc.landmark || '', granularity: d.share.location }, recipient, consent: consent.id, redFlag: GUIDE.redFlag(d.text) ? true : false, channel: APP.channel(), state: 'draft', timeline: [{ state: 'draft', at: DB.nowIso(), by: 'patient' }], messages: [], referrals: [], createdAt: DB.nowIso() };
    DB.put('cases', c); DB.audit('case:create', id);
    CASES.submit(c);
    draft.req = null;
    UI.go('#/case/' + id);
  }
  function autoMatch(d) {
    // Nearest available verified practitioner whose scope covers the need and who speaks the user's language (fallback: any)
    const pt = d.loc.lat != null ? d.loc : (d.loc.adminUnit ? GEO.unit(d.loc.adminUnit) : null); const lang = getLang();
    let c = DB.all('practitioners').filter(p => p.verification.state === 'verified' && p.availability !== 'on_leave' && p.availability !== 'offline_mode' && (d.need === 'other' || d.need === 'emergency_record' || p.scope.includes(d.need)));
    const byLang = c.filter(p => p.languages.includes(lang)); if (byLang.length) c = byLang;
    if (d.loc.adminUnit) { const r = GEO.regionOf(d.loc.adminUnit); const inR = c.filter(p => r && GEO.isWithin(p.adminUnit, r.id)); if (inR.length) c = inR; }
    c.sort((a, b) => (a.availability === 'available_now' ? 0 : 1) - (b.availability === 'available_now' ? 0 : 1) || ((pt ? GEO.km(pt, a) : 0) - (pt ? GEO.km(pt, b) : 0)));
    return c[0] ? { kind: 'practitioner', id: c[0].id, name: c[0].name } : null;
  }

  // ---------- Voice-first entry ----------
  function voice() { const q = UI.qs(); draft.req = null; UI.go('#/request?voice=1' + (q.to ? '&to=' + q.to : '')); }

  // ---------- Prescription flow (PHA-03/04) ----------
  function rx() {
    const q = UI.qs(); const lang = getLang();
    if (!draft.rx || (q.to && draft.rx.to !== q.to)) draft.rx = { step: 0, to: q.to || null, file: null, loc: Object.assign({}, GEO.saved() || {}), fulfil: 'collect', route: q.to ? 'selected' : 'nearest', phone: '', consent: false, notice: false, otp: false, note: '' };
    const d = draft.rx; const to = d.to ? DB.get('facilities', d.to) : null;
    const pt = d.loc.lat != null ? d.loc : (d.loc.adminUnit ? GEO.unit(d.loc.adminUnit) : null);
    const cands = to ? [to] : DB.all('facilities').filter(f => f.type === 'pharmacy' && f.verification.state === 'verified' && (d.fulfil === 'collect' || f.delivery)).map(f => ({ f, d: pt ? GEO.km(pt, f) : null })).filter(x => x.d === null || x.d < 30).sort((a, b) => (a.d || 9e9) - (b.d || 9e9)).slice(0, 3).map(x => x.f);
    let body = '';
    if (d.step === 0) body = '<div class="card"><h2>' + esc(t('rx_upload')) + '</h2><p class="small">' + esc(t('rx_note_valid')) + '</p><input type="file" id="rxFile" accept="image/*,application/pdf" capture="environment"><p class="hint">' + esc(t('attach_hint')) + '</p><div id="rxPrev">' + (d.file ? '<span class="badge b-green">✓ ' + esc(d.file.name) + ' · ' + UI.fmtBytes(d.file.size) + '</span>' : '') + '</div><label class="f">' + esc(t('notes')) + ' (' + esc(t('optional')) + ')<input type="text" id="rxNote" value="' + esc(d.note) + '"></label></div>';
    if (d.step === 1) body = '<div class="card"><h2>' + esc(t('rx_where')) + '</h2><div class="row"><button class="btn ghost" id="rGps">📍 ' + esc(t('location_gps')) + '</button><button class="btn ghost" id="rArea">🗺 ' + esc(t('location_manual')) + '</button></div><p class="small" style="margin-top:8px">' + esc(d.loc.adminUnit ? GEO.path(d.loc.adminUnit, lang) : t('any_area')) + (d.loc.lat != null ? ' · GPS ✓' : '') + '</p><h3>' + esc(t('rx_fulfil')) + '</h3><div class="choices"><button class="choice" data-ful="collect" aria-pressed="' + (d.fulfil === 'collect') + '">' + esc(t('collect')) + '</button><button class="choice" data-ful="deliver" aria-pressed="' + (d.fulfil === 'deliver') + '">' + esc(t('deliver')) + '</button></div><h3>' + esc(t('rx_pharmacies')) + '</h3>' + (cands.length ? cands.map(f => '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(f.name) + '</span>' + UI.verifBadge(f.verification) + '</div><div class="meta">' + esc(GEO.path(f.adminUnit, lang)) + (pt && GEO.km(pt, f) != null ? ' · ' + GEO.km(pt, f).toFixed(1) + ' ' + esc(t('km_away')) : '') + ' · ' + esc(f.hours) + '</div></div></div>').join('') : '<p class="err">' + esc(t('no_results')) + '</p>') + '</div>';
    if (d.step === 2) body = '<div class="card"><h2>' + esc(t('req_contact')) + '</h2><label class="f">' + esc(t('phone')) + '<input type="tel" id="rPhone" inputmode="tel" value="' + esc(d.phone) + '"></label><p class="hint">' + esc(t('phone_hint')) + '</p><h3>' + esc(t('consent_title')) + '</h3><p class="small">' + esc(t('consent_body')) + '</p><label class="check"><input type="checkbox" id="rConsent"' + (d.consent ? ' checked' : '') + '><span>' + esc(t('consent_share')) + '</span></label><label class="check"><input type="checkbox" id="rNotice"' + (d.notice ? ' checked' : '') + '><span>' + esc(t('consent_agree')) + '</span></label>' + (!navigator.onLine ? '<div class="alert amber">' + esc(t('queued_hint')) + '</div>' : '') + '</div>';
    UI.render('<h1>' + esc(t('rx_title')) + '</h1><div class="tabs" aria-hidden="true">' + [0, 1, 2].map(i => '<button tabindex="-1" aria-selected="' + (i === d.step) + '">' + (i + 1) + '</button>').join('') + '</div>' + body + '<div class="row" style="margin-top:10px">' + (d.step > 0 ? '<button class="btn ghost" id="rPrev">' + esc(t('back')) + '</button>' : '') + (d.step < 2 ? '<button class="btn primary" id="rNext">' + esc(t('next')) + '</button>' : '<button class="btn primary" id="rSend">' + esc(t('send')) + '</button>') + '</div><p class="err" id="rErr"></p>', { back: true, title: t('rx_title') });
    const err = m => $('#rErr').textContent = m;
    if (d.step === 0) { $('#rxFile').onchange = e => UI.readFile(e.target.files[0], 2 * 1048576).then(r => { d.file = r; $('#rxPrev').innerHTML = '<span class="badge b-green">✓ ' + esc(r.name) + ' · ' + UI.fmtBytes(r.size) + '</span>'; }).catch(er => err(er.message === 'size' ? t('too_large') : t('retry'))); $('#rxNote').oninput = e => d.note = e.target.value; }
    if (d.step === 1) { $('#rGps').onclick = () => GEO.gps().then(p => { const near = GEO.nearestUnit(p, 3); d.loc = Object.assign(d.loc, { lat: p.lat, lng: p.lng, acc: p.acc, adminUnit: near && near.km < 60 ? near.unit.id : d.loc.adminUnit }); GEO.save(d.loc); rx(); }).catch(() => err(t('em_gps_denied'))); $('#rArea').onclick = () => pickArea(u => { d.loc.adminUnit = u; GEO.save(d.loc); rx(); }, d.loc.adminUnit); $$('[data-ful]').forEach(b => b.onclick = () => { d.fulfil = b.getAttribute('data-ful'); rx(); }); }
    if (d.step === 2) { $('#rPhone').oninput = e => d.phone = e.target.value; $('#rConsent').onchange = e => d.consent = e.target.checked; $('#rNotice').onchange = e => d.notice = e.target.checked; }
    const prev = $('#rPrev'); if (prev) prev.onclick = () => { d.step--; rx(); };
    const next = $('#rNext'); if (next) next.onclick = () => { if (d.step === 0 && !d.file) return err(t('rx_upload') + ': ' + t('required')); if (d.step === 1 && !cands.length) return err(t('no_results')); d.step++; rx(); };
    const send = $('#rSend'); if (send) send.onclick = () => { if (!/^\+?\d{9,13}$/.test(d.phone.replace(/\s/g, ''))) return err(t('phone') + ': ' + t('required')); if (!d.consent || !d.notice) return err(t('consent_title') + ': ' + t('required')); if (!d.otp) return otp(async () => { d.otp = true; await submitRx(d, cands); }); submitRx(d, cands); };
  }
  async function submitRx(d, cands) {
    const id = DB.newId('RX'); const fid = DB.newId('AT');
    try { await DB.files.put(fid, d.file.blob, { case: id, kind: 'prescription', type: d.file.type, path: id + '/' + fid }); } catch (e) {}
    const consent = DB.put('consents', { id: DB.newId('CS'), subject: DB.deviceToken(), phoneHash: DB.hash(d.phone), purpose: 'prescription-request', recipient: cands.map(f => f.id).join(','), lang: getLang(), version: I18N_VERSION, at: DB.nowIso(), withdrawnAt: null });
    const c = { id, kind: 'request', type: 'prescription', idem: DB.newId('IDM'), device: DB.deviceToken(), phone: d.phone, name: '', lang: getLang(), need: 'medication', urgency: 'soon', text: d.note, attachments: [{ id: fid, kind: 'prescription', name: d.file.name, size: d.file.size, type: d.file.type, path: id + '/' + fid }], location: { adminUnit: d.loc.adminUnit || null, lat: d.fulfil === 'deliver' ? d.loc.lat : null, lng: d.fulfil === 'deliver' ? d.loc.lng : null, landmark: d.loc.landmark || '', granularity: d.fulfil === 'deliver' ? 'exact' : 'area' }, recipients: cands.map(f => f.id), responses: {}, chosenPharmacy: null, fulfilment: d.fulfil, consent: consent.id, channel: APP.channel(), state: 'draft', timeline: [{ state: 'draft', at: DB.nowIso(), by: 'patient' }], messages: [], createdAt: DB.nowIso() };
    DB.put('cases', c); DB.audit('case:create', id); CASES.submit(c); draft.rx = null; UI.toast(t('rx_sent'), 4000); UI.go('#/case/' + id);
  }

  // ---------- Han's products (HWC-01) ----------
  const cart = [];
  function products() {
    const q = UI.qs();
    if (q.id) return productDetail(q.id);
    const ps = DB.all('hansProducts');
    UI.render('<h1>' + esc(t('prod_title')) + '</h1><p class="muted">' + esc(t('prod_sub')) + '</p>' + (cart.length ? '<a class="btn primary block" href="#/cart">🧺 ' + esc(t('cart')) + ' (' + cart.reduce((s, x) => s + x.qty, 0) + ')</a>' : '') + '<div class="card">' + ps.map(p => '<div class="item"><div class="avatar" aria-hidden="true">🌸</div><div class="body"><div class="row between"><span class="title">' + esc(p.name) + '</span>' + UI.stockBadge(p.stock) + '</div><div class="meta">' + esc(t('category')) + ': ' + esc(p.category) + ' · ' + p.variants.map(v => esc(v.label) + ' ' + v.price + ' ETB').join(' · ') + '</div><div class="row" style="margin-top:6px"><a class="btn small ghost" href="#/products?id=' + p.id + '">' + esc(t('view')) + '</a></div></div></div>').join('') + '</div>', { title: t('prod_title') });
  }
  function productDetail(id) {
    const p = DB.get('hansProducts', id); if (!p) return UI.go('#/products');
    let variant = p.variants[0].sku, qty = 1;
    UI.render('<div class="card"><h1>' + esc(p.name) + '</h1>' + UI.stockBadge(p.stock) + '<h3>' + esc(t('prod_edu')) + '</h3><p>' + esc(p.education.use) + '</p><p class="small"><b>' + esc(p.education.safety) + '</b></p>' + UI.listenBtn(p.education.use + ' ' + p.education.safety) + '<h3>' + esc(t('prod_variants')) + '</h3><div class="choices">' + p.variants.map((v, i) => '<button class="choice" data-var="' + v.sku + '" aria-pressed="' + (i === 0) + '">' + esc(v.label) + '<br><small>' + v.price + ' ETB</small></button>').join('') + '</div><label class="f">' + esc(t('qty')) + '<input type="number" id="pQty" min="1" max="20" value="1" style="max-width:120px"></label><div class="row" style="margin-top:8px"><button class="btn primary" id="pAdd"' + (p.stock === 'unavailable' ? ' disabled' : '') + '>' + esc(t('add_cart')) + '</button><a class="btn ghost" href="#/cart">' + esc(t('cart')) + ' (' + cart.reduce((s, x) => s + x.qty, 0) + ')</a></div></div>', { back: true, title: p.name });
    UI.bindListen();
    $$('[data-var]').forEach(b => b.onclick = () => { variant = b.getAttribute('data-var'); $$('[data-var]').forEach(x => x.setAttribute('aria-pressed', x === b)); });
    $('#pQty').onchange = e => qty = Math.max(1, Math.min(20, +e.target.value || 1));
    $('#pAdd').onclick = () => { const v = p.variants.find(x => x.sku === variant); const ex = cart.find(x => x.sku === variant); if (ex) ex.qty += qty; else cart.push({ productId: p.id, name: p.name, sku: v.sku, label: v.label, price: v.price, qty }); UI.toast(t('add_cart') + ' ✓'); UI.go('#/cart'); };
  }
  function cartView() {
    const total = cart.reduce((s, x) => s + x.price * x.qty, 0);
    UI.render('<h1>' + esc(t('cart')) + '</h1>' + (cart.length ? '<div class="card">' + cart.map((x, i) => '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(x.name) + ' · ' + esc(x.label) + '</span><span>' + (x.price * x.qty) + ' ETB</span></div><div class="meta">' + x.qty + ' × ' + x.price + ' ETB <button class="linkbtn" data-rm="' + i + '">' + esc(t('remove')) + '</button></div></div></div>').join('') + '<div class="row between" style="margin-top:8px"><b>' + esc(t('total')) + '</b><b>' + total + ' ETB</b></div></div><div class="card"><h2>' + esc(t('checkout')) + '</h2><p class="hint">' + esc(t('guest_hint')) + '</p><label class="f">' + esc(t('phone')) + '<input type="tel" id="oPhone" inputmode="tel"></label><label class="f">' + esc(t('name_optional')) + '<input type="text" id="oName"></label><div class="choices"><button class="choice" data-ful="collect" aria-pressed="true">' + esc(t('collect')) + '</button><button class="choice" data-ful="deliver" aria-pressed="false">' + esc(t('deliver')) + '</button></div><label class="f">' + esc(t('delivery_address')) + '<textarea id="oAddr" style="min-height:70px">' + esc(GEO.saved() && GEO.saved().adminUnit ? GEO.path(GEO.saved().adminUnit, getLang()) + (GEO.saved().landmark ? ', ' + GEO.saved().landmark : '') : '') + '</textarea></label><label class="check"><input type="checkbox" id="oConsent"><span>' + esc(t('consent_share')) + '</span></label><p class="small">' + esc(t('pay_later')) + '</p><button class="btn primary block" id="oSend">' + esc(t('checkout')) + '</button><p class="err" id="oErr"></p></div>' : '<div class="alert blue">' + esc(t('empty_cart')) + '</div><a class="btn ghost" href="#/products">' + esc(t('prod_title')) + '</a>'), { back: true, title: t('cart') });
    let ful = 'collect';
    $$('[data-rm]').forEach(b => b.onclick = () => { cart.splice(+b.getAttribute('data-rm'), 1); cartView(); });
    $$('[data-ful]').forEach(b => b.onclick = () => { ful = b.getAttribute('data-ful'); $$('[data-ful]').forEach(x => x.setAttribute('aria-pressed', x === b)); });
    const send = $('#oSend'); if (send) send.onclick = () => {
      const phone = $('#oPhone').value.trim(); if (!/^\+?\d{9,13}$/.test(phone.replace(/\s/g, ''))) return $('#oErr').textContent = t('phone') + ': ' + t('required'); if (!$('#oConsent').checked) return $('#oErr').textContent = t('consent_title') + ': ' + t('required');
      otp(() => { const o = { id: DB.newId('OR'), kind: 'order', type: 'hans', idem: DB.newId('IDM'), device: DB.deviceToken(), buyer: { phone, name: $('#oName').value.trim() }, seller: 'HANS', items: cart.map(x => Object.assign({}, x)), fulfilment: ful, address: $('#oAddr').value.trim(), total: total, fee: 0, paymentState: 'pay_on_fulfilment', state: 'draft', timeline: [{ state: 'draft', at: DB.nowIso(), by: 'patient' }], lang: getLang(), channel: APP.channel(), createdAt: DB.nowIso() }; DB.put('orders', o); CASES.transition(o, 'pending_confirmation', 'patient', '', 'order'); DB.notify('HANS', 'New product order ' + o.id, '#/pro/order/' + o.id); cart.length = 0; UI.toast(t('order_placed'), 4000); UI.go('#/order/' + o.id); });
    };
  }

  // ---------- Wellbeing booking (WEL-01) ----------
  function book(id) {
    const w = DB.get('wellbeing', id); if (!w || w.verification.state !== 'verified') return UI.go('#/find?type=wellbeing');
    UI.render('<h1>' + esc(t('wel_book')) + ': ' + esc(w.name) + '</h1><div class="alert pink small">' + esc(t('wel_note')) + '</div><div class="card"><label class="f">' + esc(t('wel_time')) + '<input type="datetime-local" id="bTime"></label><label class="f">' + esc(t('phone')) + '<input type="tel" id="bPhone" inputmode="tel"></label><label class="f">' + esc(t('name_optional')) + '<input type="text" id="bName"></label><label class="f">' + esc(t('delivery_address')) + '<textarea id="bAddr" style="min-height:70px"></textarea></label><p class="small"><b>' + esc(t('wel_safeguards')) + ':</b> ' + esc(w.safeguards) + '<br><b>' + esc(t('wel_cancel_terms')) + ':</b> ' + esc(w.cancelTerms) + '</p><label class="check"><input type="checkbox" id="bConsent"><span>' + esc(t('consent_share')) + '</span></label><button class="btn primary block" id="bSend">' + esc(t('wel_book')) + '</button><p class="err" id="bErr"></p></div>', { back: true, title: t('wel_book') });
    $('#bSend').onclick = () => { const phone = $('#bPhone').value.trim(); if (!/^\+?\d{9,13}$/.test(phone.replace(/\s/g, ''))) return $('#bErr').textContent = t('phone') + ': ' + t('required'); if (!$('#bConsent').checked) return $('#bErr').textContent = t('consent_title') + ': ' + t('required'); otp(() => { const o = { id: DB.newId('BK'), kind: 'order', type: 'wellbeing', idem: DB.newId('IDM'), device: DB.deviceToken(), buyer: { phone, name: $('#bName').value.trim() }, seller: w.id, items: [{ name: w.service, price: w.price, qty: 1 }], when: $('#bTime').value, address: $('#bAddr').value.trim(), addressReleased: false, total: 0, fee: 0, paymentState: 'pay_on_fulfilment', state: 'draft', timeline: [{ state: 'draft', at: DB.nowIso(), by: 'patient' }], lang: getLang(), channel: APP.channel(), createdAt: DB.nowIso() }; DB.put('orders', o); CASES.transition(o, 'pending_confirmation', 'patient', '', 'order'); DB.notify(w.id, 'New booking ' + o.id, '#/pro/order/' + o.id); UI.toast(t('book_confirm'), 4000); UI.go('#/order/' + o.id); }); };
  }

  // ---------- My requests and orders (PAT-06) ----------
  function cases() {
    const dev = DB.deviceToken(); const lang = getLang();
    const cs = DB.all('cases').filter(c => c.device === dev).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    const os = DB.all('orders').filter(o => o.device === dev).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
    UI.render('<h1>' + esc(t('cases_title')) + '</h1>' + (!cs.length && !os.length ? '<div class="alert blue">' + esc(t('cases_empty')) + '</div>' : '') +
      (cs.length ? '<h2>' + esc(t('my_requests')) + '</h2><div class="card">' + cs.map(c => '<a class="item' + (c.state === 'queued_offline' ? ' unsent' : '') + '" href="#/case/' + c.id + '" style="text-decoration:none;color:inherit"><div class="body"><div class="row between"><span class="title">' + esc(c.id) + ' · ' + esc(t(c.type === 'prescription' ? 'rx_title' : 'need_' + (c.need || 'other'))) + '</span>' + UI.stateBadge(c.state) + '</div><div class="meta">' + esc(UI.fmtDate(c.createdAt, true)) + (c.recipient ? ' · ' + esc(c.recipient.name) : '') + (c.state === 'queued_offline' ? ' · <b class="err">' + esc(t('not_sent')) + '</b>' : '') + '</div></div></a>').join('') + '</div>' : '') +
      (os.length ? '<h2>' + esc(t('my_orders')) + '</h2><div class="card">' + os.map(o => '<a class="item" href="#/order/' + o.id + '" style="text-decoration:none;color:inherit"><div class="body"><div class="row between"><span class="title">' + esc(o.id) + ' · ' + esc(o.type === 'hans' ? t('prod_title') : t('wel_title')) + '</span>' + UI.stateBadge(o.state, 'order') + '</div><div class="meta">' + esc(UI.fmtDate(o.createdAt, true)) + ' · ' + o.items.map(i => esc(i.name)).join(', ') + '</div></div></a>').join('') + '</div>' : '') +
      '<div class="card"><h3>' + esc(t('track_code')) + '</h3><p class="hint">' + esc(t('track_hint')) + '</p><div class="row"><input type="text" id="trk" class="in" style="flex:1" placeholder="RQ-…"><button class="btn" id="trkGo">' + esc(t('view')) + '</button></div></div>', { title: t('cases_title') });
    $('#trkGo').onclick = () => { const v = $('#trk').value.trim().toUpperCase(); if (DB.get('cases', v)) UI.go('#/case/' + v); else if (DB.get('orders', v)) UI.go('#/order/' + v); else UI.toast(t('no_results')); };
  }
  function timeline(obj, kind) { return '<ul class="tl">' + (obj.timeline || []).map((s, i, arr) => '<li class="' + (i === arr.length - 1 ? 'cur' : 'done') + '"><b>' + esc(t((kind === 'order' ? 'os_' : 'st_') + s.state.replace('queued_offline', 'queued').replace('pending_confirmation', 'pending').replace('payment_pending', 'paypending').replace('ready_for_collection', 'ready').replace('assigned_for_delivery', 'assigned').replace('under_review', 'review').replace('clarification_requested', 'clarify'))) + '</b> <span class="muted small">' + esc(UI.fmtDate(s.at, true)) + (s.note ? ' · ' + esc(s.note) : '') + '</span></li>').join('') + '</ul>'; }
  async function caseView(id) {
    const c = DB.get('cases', id); if (!c) return UI.go('#/cases');
    const mine = c.device === DB.deviceToken(); const lang = getLang();
    const rec = c.recipient ? c.recipient.name : (c.recipients || []).map(r => (DB.get('facilities', r) || {}).name).join(', ');
    UI.render('<div class="card' + (c.state === 'queued_offline' ? ' unsent' : '') + '"><div class="row between"><h1 style="margin:0">' + esc(c.id) + '</h1>' + UI.stateBadge(c.state) + '</div><p class="muted">' + esc(t(c.type === 'prescription' ? 'rx_title' : 'need_' + (c.need || 'other'))) + ' · ' + esc(UI.fmtDate(c.createdAt, true)) + ' · ' + esc(t('case_with')) + ' ' + esc(rec || t('responder_auto')) + '</p>' +
      (c.state === 'queued_offline' ? '<div class="alert amber"><b>' + esc(t('not_sent')) + '.</b> ' + esc(t('queued_hint')) + '<div class="row" style="margin-top:8px"><button class="btn primary" id="sendNow">' + esc(t('send_now')) + '</button></div></div>' : c.state === 'received' || c.state === 'submitted' ? '<div class="alert green">' + esc(t('sent_ok')) + ' ' + esc(t('sent_ref')) + ': <b>' + esc(c.id) + '</b></div>' : '') +
      (c.redFlag ? '<div class="alert red small"><b>' + esc(t('red_flag')) + '</b> · <a href="#/emergency">' + esc(t('t_emergency')) + '</a></div>' : '') +
      (c.referral && mine && c.referral.consent === null ? '<div class="alert blue"><b>' + esc(t('st_referred')) + ' → ' + esc(c.referral.toName) + '</b><p class="small">' + esc(c.referral.reason || '') + '</p><p class="small">' + esc(t('pro_transfer_consent')) + '</p><div class="row"><button class="btn success small" id="refYes">' + esc(t('yes')) + ', ' + esc(t('consent_share')).split(' ').slice(0, 3).join(' ') + '</button><button class="btn ghost small" id="refNo">' + esc(t('no')) + '</button></div></div>' : '') +
      '<h3>' + esc(t('case_timeline')) + '</h3>' + timeline(c) +
      (c.type === 'prescription' && Object.keys(c.responses || {}).length ? '<h3>' + esc(t('rx_pharmacies')) + '</h3>' + Object.keys(c.responses).map(ph => { const r = c.responses[ph]; const f = DB.get('facilities', ph) || {}; return '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(f.name) + '</span><span class="badge ' + (r.status === 'full' ? 'b-green' : r.status === 'unavailable' ? 'b-red' : 'b-amber') + '">' + esc(t('rx_' + (r.status === 'unavailable' ? 'unavail' : r.status))) + '</span></div><div class="meta">' + esc(r.note || '') + (r.prepTime ? ' · ' + esc(t('prep_time')) + ': ' + esc(r.prepTime) : '') + '</div>' + (!c.chosenPharmacy && (r.status === 'full' || r.status === 'partial') && mine ? '<button class="btn small primary" data-choose="' + ph + '">' + esc(t('rx_choose_pharmacy')) + '</button>' : c.chosenPharmacy === ph ? '<span class="badge b-green">✓</span>' : '') + '</div></div>'; }).join('') : '') +
      '<h3>' + esc(t('case_messages')) + '</h3><div class="chat">' + (c.messages || []).map(m => '<div class="msg ' + (m.from === 'patient' ? 'me' : 'ai') + '"><div class="who">' + esc(m.from === 'patient' ? (mine ? 'Me' : 'Patient') : m.by || 'Responder') + ' · ' + esc(UI.fmtDate(m.at, true)) + '</div>' + esc(m.text) + (m.attachment ? '<div id="att-' + m.attachment + '"></div>' : '') + '</div>').join('') + '</div>' +
      (mine && !/cancelled|closed|expired|completed/.test(c.state) ? '<div class="row"><input type="text" id="cReply" class="in" style="flex:1" placeholder="' + esc(t('case_reply')) + '"><button class="btn" id="cSend">' + esc(t('send')) + '</button></div>' : '') +
      (c.attachments && c.attachments.length ? '<h3>' + esc(t('case_attachments')) + '</h3><div id="atts">' + c.attachments.map(a => '<div class="small" id="att-' + a.id + '">' + esc(a.kind) + ' · ' + UI.fmtBytes(a.size) + '</div>').join('') + '</div>' : '') +
      '</div>' + (mine ? '<div class="row">' + (!/cancelled|closed|expired|completed/.test(c.state) ? '<button class="btn ghost" id="cCancel">' + esc(t('case_cancel')) + '</button>' : '') + '<a class="btn ghost" href="#/complaint?case=' + c.id + '">' + esc(t('case_complaint')) + '</a></div>' : ''), { back: true, title: c.id });
    for (const a of (c.attachments || [])) { try { const f = await DB.files.get(a.id, a.path); const el = $('#att-' + a.id); if (f && el) { const url = URL.createObjectURL(f.blob); el.innerHTML += f.blob.type.startsWith('audio') ? '<audio controls src="' + url + '"></audio>' : f.blob.type === 'application/pdf' ? '<a href="' + url + '" target="_blank">PDF</a>' : '<img src="' + url + '" alt="" style="max-height:220px;border-radius:8px">'; } } catch (e) {} }
    const sn = $('#sendNow'); if (sn) sn.onclick = () => { if (!navigator.onLine) return UI.toast(t('offline')); CASES.submit(c); caseView(id); };
    const cs = $('#cSend'); if (cs) cs.onclick = () => { const v = $('#cReply').value.trim(); if (!v) return; c.messages.push({ from: 'patient', text: v, at: DB.nowIso() }); DB.put('cases', c); if (c.recipient) DB.notify(c.recipient.id, 'Patient message on ' + c.id, '#/pro/case/' + c.id); caseView(id); };
    const cc = $('#cCancel'); if (cc) cc.onclick = () => UI.confirm(t('case_cancel') + '?', () => { CASES.transition(c, 'cancelled', 'patient'); caseView(id); });
    const ry = $('#refYes'); if (ry) ry.onclick = () => { c.referral.consent = 'approved'; c.referral.consentAt = DB.nowIso(); DB.put('consents', { id: DB.newId('CS'), subject: c.device, phoneHash: DB.hash(c.phone), purpose: 'referral-transfer', recipient: c.referral.to, lang: getLang(), version: I18N_VERSION, at: DB.nowIso(), withdrawnAt: null }); DB.put('cases', c); DB.audit('referral:consent', c.id, { result: 'approved' }); DB.notify(c.referral.to, 'Referral ' + c.id + ' awaiting your acceptance', '#/pro/case/' + c.id); caseView(id); };
    const rn = $('#refNo'); if (rn) rn.onclick = () => { c.referral.consent = 'declined'; DB.put('cases', c); DB.audit('referral:consent', c.id, { result: 'declined' }); CASES.transition(c, 'received', 'patient', 'referral declined'); if (c.recipient) DB.notify(c.recipient.id, 'Referral declined by patient on ' + c.id, '#/pro/case/' + c.id); caseView(id); };
    $$('[data-choose]').forEach(b => b.onclick = () => { c.chosenPharmacy = b.getAttribute('data-choose'); DB.put('cases', c); DB.notify(c.chosenPharmacy, 'Patient chose your pharmacy for ' + c.id, '#/pro/case/' + c.id); const o = { id: DB.newId('OR'), kind: 'order', type: 'pharmacy', idem: DB.newId('IDM'), device: c.device, buyer: { phone: c.phone, name: c.name }, seller: c.chosenPharmacy, caseId: c.id, items: [{ name: t('rx_title') + ' ' + c.id, price: 0, qty: 1 }], fulfilment: c.fulfilment, address: c.location.landmark || GEO.path(c.location.adminUnit, lang), total: 0, fee: 0, paymentState: 'pay_on_fulfilment', state: 'draft', timeline: [{ state: 'draft', at: DB.nowIso(), by: 'patient' }], lang: c.lang, channel: c.channel, createdAt: DB.nowIso() }; DB.put('orders', o); CASES.transition(o, 'pending_confirmation', 'patient', '', 'order'); c.orderId = o.id; DB.put('cases', c); UI.go('#/order/' + o.id); });
  }
  function orderView(id) {
    const o = DB.get('orders', id); if (!o) return UI.go('#/cases'); const mine = o.device === DB.deviceToken();
    const seller = o.seller === 'HANS' ? "Han's With Care" : ((DB.get('facilities', o.seller) || DB.get('wellbeing', o.seller) || {}).name || o.seller);
    UI.render('<div class="card"><div class="row between"><h1 style="margin:0">' + esc(o.id) + '</h1>' + UI.stateBadge(o.state, 'order') + '</div><p class="muted">' + esc(seller) + ' · ' + esc(UI.fmtDate(o.createdAt, true)) + '</p><div class="alert green small">' + esc(t('order_placed')) + ' ' + esc(t('order_ref')) + ': <b>' + esc(o.id) + '</b></div><table class="tbl">' + o.items.map(i => '<tr><td>' + esc(i.name) + (i.label ? ' · ' + esc(i.label) : '') + '</td><td>' + i.qty + '</td><td>' + (typeof i.price === 'number' ? i.price * i.qty + ' ETB' : esc(i.price)) + '</td></tr>').join('') + '<tr><th>' + esc(t('total')) + '</th><td></td><th>' + (o.total ? o.total + ' ETB' : '-') + '</th></tr></table><p class="small">' + esc(t(o.fulfilment === 'deliver' ? 'deliver' : 'collect')) + (o.when ? ' · ' + esc(o.when.replace('T', ' ')) : '') + '<br>' + esc(t('pay_later')) + '</p><h3>' + esc(t('case_timeline')) + '</h3>' + timeline(o, 'order') + '</div>' + (mine && CASES.can('order', o.state, 'cancelled') ? '<button class="btn ghost" id="oCancel">' + esc(t('cancel')) + '</button>' : ''), { back: true, title: o.id });
    const oc = $('#oCancel'); if (oc) oc.onclick = () => UI.confirm(t('cancel') + '?', () => { CASES.transition(o, 'cancelled', 'patient', '', 'order'); orderView(id); });
  }

  // ---------- Guide (AI-01..03) ----------
  const chat = [];
  function guide() {
    if (!chat.length) chat.push({ who: 'ai', text: t('guide_disclose') });
    UI.render('<h1>' + esc(t('guide_title')) + '</h1><div class="alert blue small">' + esc(t('guide_disclose')) + '</div><div class="chat" id="chat">' + chat.map(m => '<div class="msg ' + m.who + '"><div class="who">' + (m.who === 'me' ? 'Me' : 'Guide · ' + GUIDE.VERSION) + '</div>' + esc(m.text) + (m.title ? '<br><b>' + esc(m.title) + '</b>' : '') + (m.source ? '<div class="small muted">' + esc(t('guide_kb_source')) + ': ' + esc(m.source) + (m.translated === false ? ' · EN' : '') + '</div>' : '') + (m.actions ? '<div class="quick">' + m.actions.map(a => '<a class="btn small ' + (a.cls || 'ghost') + '" href="' + a.to + '">' + esc(a.label) + '</a>').join('') + '</div>' : '') + '</div>').join('') + '</div>' +
      '<div class="quick">' + [['guide_q_emergency','#/emergency'],['guide_q_find','#/find?type=practitioner'],['guide_q_pharmacy','#/find?type=pharmacy'],['guide_q_products','#/products'],['guide_q_period','']].map(x => '<button data-q="' + x[0] + '" data-to="' + x[1] + '">' + esc(t(x[0])) + '</button>').join('') + '</div>' +
      '<div class="row"><input type="text" id="gIn" class="in" style="flex:1" placeholder="' + esc(t('guide_placeholder')) + '"><button class="btn primary" id="gSend">' + esc(t('send')) + '</button></div><div class="row" style="margin-top:8px"><a class="btn ghost small" href="#/find?type=practitioner">👤 ' + esc(t('guide_human')) + '</a>' + (chat.filter(m => m.who === 'me').length ? '<a class="btn small" href="#/request?reset=1&summary=1">' + esc(t('guide_send_summary')) + '</a>' : '') + '</div>', { title: t('guide_title') });
    const ask = text => { chat.push({ who: 'me', text }); const r = GUIDE.reply(text); chat.push({ who: 'ai', text: r.text, title: r.title, source: r.source, translated: r.translated, actions: r.actions }); guide(); const el = $('#chat'); if (el) el.lastElementChild.scrollIntoView({ block: 'nearest' }); };
    $('#gSend').onclick = () => { const v = $('#gIn').value.trim(); if (v) ask(v); };
    $('#gIn').onkeydown = e => { if (e.key === 'Enter') $('#gSend').click(); };
    $$('[data-q]').forEach(b => b.onclick = () => { const to = b.getAttribute('data-to'); if (to) UI.go(to); else ask(t(b.getAttribute('data-q'))); });
  }

  // ---------- Menu and static pages ----------
  function menu() {
    const s = DB.session(); const packs = GEO.packs();
    UI.render('<h1>' + esc(t('menu_title')) + '</h1><div class="card">' + [['#/lang','🌐',t('menu_lang') + ' · ' + (LANGS.find(l => l.code === getLang()) || {}).native],['#/packs','📦',t('menu_packs') + (packs.length ? ' (' + packs.length + ')' : '')],['#/cases','📋',t('cases_title')],['#/complaint','⚠️',t('menu_complaint')],['#/rights','🔐',t('menu_data_rights')],['#/privacy','📜',t('menu_privacy')],['#/about','ℹ️',t('menu_about')]].map(x => '<a class="item" href="' + x[0] + '" style="text-decoration:none;color:inherit"><span class="avatar" aria-hidden="true">' + x[1] + '</span><div class="body"><div class="title">' + esc(x[2]) + '</div></div></a>').join('') + '</div>' +
      '<div class="card"><a class="item" href="#/pro" style="text-decoration:none;color:inherit"><span class="avatar" aria-hidden="true">🩺</span><div class="body"><div class="title">' + esc(t('menu_pro')) + '</div><div class="meta">' + esc(s ? s.name + ' · ' + t('role_' + (s.role === 'pharmacist' ? 'pharmacist' : s.role === 'nurse' ? 'nurse' : s.role === 'wellbeing' ? 'wellbeing' : s.role === 'doctor' ? 'doctor' : 'admin')) : '') + '</div></div></a>' + (s ? '<button class="linkbtn" id="signout">' + esc(t('signout')) + '</button>' : '') + '</div><div id="installBox"></div><p class="hint">' + esc(t('owner_notice')) + '</p><p class="hint">v' + esc(SEED.version) + ' · i18n ' + I18N_VERSION + ' · ' + (DB.remote && DB.remote.enabled ? 'cloud sync' : esc(t('demo_banner'))) + '</p>', { title: t('menu_title') });
    const so = $('#signout'); if (so) so.onclick = () => { DB.logout(); menu(); };
    APP.installPrompt('installBox');
  }
  function packs() {
    const regions = GEO.children('ET'); const have = GEO.packs(); const lang = getLang();
    UI.render('<h1>' + esc(t('packs_title')) + '</h1><p class="small">' + esc(t('packs_hint')) + '</p><div class="card">' + regions.map(r => { const n = DB.all('emergency').filter(e => e.jurisdiction === r.id || e.jurisdiction === 'ET').length + DB.all('facilities').filter(f => GEO.isWithin(f.adminUnit, r.id)).length; return '<div class="item"><div class="body"><div class="row between"><span class="title">' + esc(GEO.label(r, lang)) + '</span>' + (have.includes(r.id) ? '<span class="badge b-green">✓ ' + esc(t('pack_downloaded')) + '</span>' : '') + '</div><div class="meta">' + n + ' records</div><div class="row" style="margin-top:6px">' + (have.includes(r.id) ? '<button class="btn small ghost" data-rm="' + r.id + '">' + esc(t('pack_remove')) + '</button>' : '<button class="btn small" data-dl="' + r.id + '">⬇ ' + esc(t('pack_download')) + '</button>') + '</div></div></div>'; }).join('') + '</div>', { back: true, title: t('packs_title') });
    $$('[data-dl]').forEach(b => b.onclick = () => { b.disabled = true; GEO.downloadPack(b.getAttribute('data-dl')).then(() => { UI.toast(t('pack_downloaded')); packs(); }).catch(() => { UI.toast(t('retry')); packs(); }); });
    $$('[data-rm]').forEach(b => b.onclick = () => { GEO.removePack(b.getAttribute('data-rm')); packs(); });
  }
  function page(key, titleKey) { UI.render('<h1>' + esc(t(titleKey)) + '</h1><div class="card"><p>' + esc(t(key)) + '</p>' + UI.listenBtn(t(key)) + (key === 'about_body' ? '<hr class="divider"><p class="small muted">' + esc(t('owner_notice')) + ' © ' + new Date().getFullYear() + ' Han\'s With Care Manufacturing.</p><p class="small muted">v' + esc(SEED.version) + ' · i18n ' + I18N_VERSION + (DB.remote && DB.remote.enabled ? ' · cloud sync' : ' · ' + esc(t('demo_banner'))) + '</p>' : '') + '</div>', { back: true, title: t(titleKey) }); UI.bindListen(); }
  function complaint() {
    const q = UI.qs();
    UI.render('<h1>' + esc(t('complaint_title')) + '</h1><div class="card"><label class="f">' + esc(t('complaint_type')) + '<select id="cType">' + ['unsafe','wrong_person','impersonation','stock','delay','data','other'].map(x => '<option value="' + x + '">' + esc(t('c_' + x)) + '</option>').join('') + '</select></label><label class="f">' + esc(t('case_ref')) + ' (' + esc(t('optional')) + ')<input type="text" id="cCase" value="' + esc(q.case || '') + '"></label><label class="f">' + esc(t('complaint_text')) + '<textarea id="cText"></textarea></label><label class="f">' + esc(t('phone')) + ' (' + esc(t('optional')) + ')<input type="tel" id="cPhone"></label><button class="btn primary block" id="cSend">' + esc(t('send')) + '</button></div>', { back: true, title: t('complaint_title') });
    $('#cSend').onclick = () => { const text = $('#cText').value.trim(); if (!text) return; DB.put('complaints', { id: DB.newId('CP'), type: $('#cType').value, caseId: $('#cCase').value.trim(), text, phone: $('#cPhone').value.trim(), device: DB.deviceToken(), lang: getLang(), state: 'open', at: DB.nowIso() }); DB.audit('complaint:create', ''); DB.notify('safety', 'New complaint', '#/admin?tab=complaints'); UI.toast(t('complaint_sent'), 4000); UI.go('#/'); };
  }
  function rights() {
    UI.render('<h1>' + esc(t('menu_data_rights')) + '</h1><div class="card"><p>' + esc(t('rights_body')) + '</p><label class="f">' + esc(t('type')) + '<select id="rType"><option value="access">Access</option><option value="correction">Correction</option><option value="deletion">Deletion</option><option value="restriction">Restriction</option><option value="objection">Objection</option></select></label><label class="f">' + esc(t('phone')) + '<input type="tel" id="rPhone"></label><label class="f">' + esc(t('notes')) + '<textarea id="rText"></textarea></label><button class="btn primary block" id="rSend">' + esc(t('send')) + '</button></div>', { back: true, title: t('menu_data_rights') });
    $('#rSend').onclick = () => { const phone = $('#rPhone').value.trim(); if (!phone) return; DB.put('complaints', { id: DB.newId('DR'), type: 'data-right:' + $('#rType').value, text: $('#rText').value.trim(), phone, device: DB.deviceToken(), lang: getLang(), state: 'open', at: DB.nowIso() }); DB.notify('privacy', 'Data subject request', '#/admin?tab=complaints'); UI.toast(t('complaint_sent'), 4000); UI.go('#/menu'); };
  }
  return { langChooser, home, emergency, find, profile, request, voice, rx, products, cartView, book, cases, caseView, orderView, guide, menu, packs, page, complaint, rights, pickArea, otp, timeline, draft };
})();
