/* Han's With Care, seed data for the demonstration build.
   IMPORTANT: geography, facilities and emergency numbers below are a SEED loaded from
   public sources on 2026-09-01 (ToR Annex B/F). They are not the national gazetteer
   deliverable (D3). Every record carries source/version/verification fields so that
   administrators can replace it with authority-validated data without a code release.
   Practitioners, pharmacies and wellbeing providers are FICTIONAL demonstration records. */
const SEED_VERSION = '2026.09.01-seed';
const SEED_DATE = '2026-09-01';

function _geoBuild() {
  const U = []; // administrative units
  const add = (id, level, parent, en, local, lat, lng, extra) => U.push(Object.assign({
    id, level, parent, name: en, local: local || '', aliases: [], lat, lng, urban: level >= 4,
    geomConfidence: 'approx-centroid', source: 'Public reference / ToR Annex B', sourceUrl: 'https://data.moa.gov.et/dataset/ethiopian-administrative-boundary',
    version: SEED_VERSION, obtained: SEED_DATE, verifiedAt: null, verifiedBy: null, active: true, pack: parent === 'ET' ? id : null
  }, extra || {}));
  add('ET', 0, null, 'Ethiopia', 'ኢትዮጵያ', 9.145, 40.489);
  // level 1: regional states and city administrations
  const R = [
    ['AA','Addis Ababa city administration','አዲስ አበባ',9.03,38.74,'am'], ['DD','Dire Dawa city administration','ድሬዳዋ',9.6,41.86,'am'],
    ['OR','Oromia','Oromiyaa',8.54,39.27,'om'], ['AM','Amhara','አማራ',11.6,37.39,'am'], ['TG','Tigray','ትግራይ',13.49,39.47,'ti'],
    ['SD','Sidama','Sidaama',7.06,38.48,'am'], ['SM','Somali','Soomaali',9.35,42.8,'so'], ['AF','Afar','Qafar',11.79,41.01,'am'],
    ['BG','Benishangul-Gumuz','ቤኒሻንጉል ጉሙዝ',10.07,34.53,'am'], ['GM','Gambela','ጋምቤላ',8.25,34.59,'am'], ['HR','Harari','ሐረሪ',9.31,42.12,'am'],
    ['CE','Central Ethiopia','ማዕከላዊ ኢትዮጵያ',7.55,37.85,'am'], ['SE','South Ethiopia','ደቡብ ኢትዮጵያ',6.86,37.76,'am'], ['SW',"South West Ethiopia Peoples'",'ደቡብ ምዕራብ ኢትዮጵያ ሕዝቦች',7.27,36.24,'am']
  ];
  R.forEach(r => add(r[0], 1, 'ET', r[1], r[2], r[3], r[4], { urban: false, primaryLang: r[5], pack: r[0] }));
  // level 3/4 hubs from Annex B (city administrations / towns), parent = region (zone level skipped where unknown)
  const H = [
    ['DD','DD-DIRE','Dire Dawa','ድሬዳዋ',9.6,41.86],
    ['OR','OR-ADAMA','Adama','Adaamaa',8.54,39.27],['OR','OR-BISH','Bishoftu','Bishooftuu',8.75,38.98],['OR','OR-JIMMA','Jimma','Jimmaa',7.67,36.83],['OR','OR-SHASH','Shashamane','Shaashamannee',7.2,38.6],['OR','OR-NEK','Nekemte','Naqamtee',9.09,36.55],['OR','OR-AMBO','Ambo','Amboo',8.98,37.85],['OR','OR-ASELLA','Asella','Asallaa',7.95,39.13],['OR','OR-ROBE','Bale Robe','Roobee',7.12,40.0],
    ['AM','AM-BDR','Bahir Dar','ባሕር ዳር',11.6,37.39],['AM','AM-GON','Gondar','ጎንደር',12.6,37.47],['AM','AM-DES','Dessie','ደሴ',11.13,39.63],['AM','AM-KOM','Kombolcha','ኮምቦልቻ',11.08,39.74],['AM','AM-DBR','Debre Birhan','ደብረ ብርሃን',9.68,39.53],['AM','AM-DMK','Debre Markos','ደብረ ማርቆስ',10.34,37.72],['AM','AM-WOL','Woldiya','ወልድያ',11.83,39.6],
    ['TG','TG-MEK','Mekelle','መቐለ',13.49,39.47],['TG','TG-ADG','Adigrat','ዓዲግራት',14.28,39.46],['TG','TG-AXM','Axum','ኣኽሱም',14.13,38.72],['TG','TG-SHR','Shire','ሽረ',14.1,38.28],['TG','TG-ADW','Adwa','ዓድዋ',14.17,38.9],['TG','TG-ALM','Alamata','ኣላማጣ',12.42,39.56],
    ['SD','SD-HAW','Hawassa','ሀዋሳ',7.06,38.48],
    ['SM','SM-JIG','Jigjiga','Jigjiga',9.35,42.8],['SM','SM-GODE','Gode','Godey',5.95,43.45],['SM','SM-KD','Kebri Dehar','Qabridahar',6.74,44.28],['SM','SM-DEG','Degehabur','Dhagaxbuur',8.22,43.56],
    ['AF','AF-SEM','Semera-Logiya','ሰመራ ሎጊያ',11.79,41.01],['AF','AF-ASA','Asayita','አሳይታ',11.57,41.44],['AF','AF-DUB','Dubti','ዱብቲ',11.73,41.08],
    ['BG','BG-ASO','Asosa','አሶሳ',10.07,34.53],['BG','BG-GB','Gilgel Beles','ግልገል በለስ',11.18,36.37],
    ['GM','GM-GAM','Gambela','ጋምቤላ',8.25,34.59],
    ['HR','HR-HAR','Harar','ሐረር',9.31,42.12],
    ['CE','CE-HOS','Hossana','ሆሳዕና',7.55,37.85],['CE','CE-WOLK','Wolkite','ወልቂጤ',8.28,37.78],['CE','CE-BUT','Butajira','ቡታጅራ',8.12,38.37],['CE','CE-WOR','Worabe','ወራቤ',7.94,38.14],
    ['SE','SE-SODO','Wolaita Sodo','ወላይታ ሶዶ',6.86,37.76],['SE','SE-ARBA','Arba Minch','አርባ ምንጭ',6.04,37.55],['SE','SE-DILLA','Dilla','ዲላ',6.41,38.31],['SE','SE-JINKA','Jinka','ጂንካ',5.78,36.57],['SE','SE-SAWLA','Sawla','ሳውላ',6.3,36.88],['SE','SE-KARAT','Karat','ካራት',5.25,37.48],
    ['SW','SW-BONGA','Bonga','ቦንጋ',7.27,36.24],['SW','SW-MIZAN','Mizan Aman','ሚዛን አማን',6.99,35.58],['SW','SW-TEPI','Tepi','ቴፒ',7.2,35.42]
  ];
  H.forEach(h => add(h[1], 3, h[0], h[2], h[3], h[4], h[5], { urban: true, pack: h[0] }));
  // Addis Ababa sub-cities (level 4) and sample woredas/kebeles (level 5/6) for the pilot
  const AASC = [['AA-ADK','Addis Ketema','አዲስ ከተማ',9.04,38.73],['AA-AKK','Akaky Kaliti','አቃቂ ቃሊቲ',8.9,38.78],['AA-ARA','Arada','አራዳ',9.04,38.75],['AA-BOL','Bole','ቦሌ',8.99,38.79],['AA-GUL','Gullele','ጉለሌ',9.07,38.73],['AA-KIR','Kirkos','ቂርቆስ',9.01,38.76],['AA-KOL','Kolfe Keranio','ኮልፌ ቀራኒዮ',9.02,38.68],['AA-LID','Lideta','ልደታ',9.01,38.73],['AA-NSL','Nifas Silk-Lafto','ንፋስ ስልክ ላፍቶ',8.96,38.73],['AA-YEK','Yeka','የካ',9.05,38.8],['AA-LEM','Lemi Kura','ለሚ ኩራ',9.03,38.86]];
  AASC.forEach(s => add(s[0], 4, 'AA', s[1], s[2], s[3], s[4], { urban: true, pack: 'AA' }));
  for (let w = 1; w <= 3; w++) add('AA-BOL-W' + pad2(w), 5, 'AA-BOL', 'Bole Woreda ' + pad2(w), 'ቦሌ ወረዳ ' + pad2(w), 8.99 + w * 0.006, 38.79 + w * 0.006, { urban: true, pack: 'AA' });
  for (let w = 1; w <= 2; w++) add('AA-KIR-W' + pad2(w), 5, 'AA-KIR', 'Kirkos Woreda ' + pad2(w), 'ቂርቆስ ወረዳ ' + pad2(w), 9.01 + w * 0.005, 38.76 + w * 0.004, { urban: true, pack: 'AA' });
  add('AA-BOL-W01-K01', 6, 'AA-BOL-W01', 'Bole Medhanialem area', 'ቦሌ መድኃኔዓለም', 8.996, 38.79, { urban: true, pack: 'AA', aliases: ['Medhanialem', 'Bole Medhane Alem'] });
  add('AA-BOL-W01-K02', 6, 'AA-BOL-W01', 'Bole Atlas area', 'ቦሌ አትላስ', 9.0, 38.785, { urban: true, pack: 'AA', aliases: ['Atlas'] });
  add('AA-BOL-W02-K01', 6, 'AA-BOL-W02', 'Gerji', 'ገርጂ', 8.995, 38.81, { urban: true, pack: 'AA' });
  add('AA-KIR-W01-K01', 6, 'AA-KIR-W01', 'Kazanchis', 'ካዛንችስ', 9.017, 38.77, { urban: true, pack: 'AA', aliases: ['Casanchis'] });
  add('AA-KIR-W02-K01', 6, 'AA-KIR-W02', 'Meskel Square area', 'መስቀል አደባባይ', 9.01, 38.762, { urban: true, pack: 'AA' });
  // Hawassa sub-cities
  [['SD-HAW-HD','Hayk Dar','ሀይቅ ዳር',7.05,38.47],['SD-HAW-MN','Menaheriya','መናኸሪያ',7.06,38.48],['SD-HAW-MS','Misrak','ምስራቅ',7.06,38.5],['SD-HAW-TB','Tabor','ታቦር',7.04,38.49],['SD-HAW-BA','Bahil Adarash','ባህል አዳራሽ',7.07,38.47],['SD-HAW-AK','Addis Ketema','አዲስ ከተማ',7.08,38.48],['SD-HAW-HT','Hawela Tula','ሀወላ ቱላ',7.0,38.5],['SD-HAW-TU','Tula','ቱላ',6.98,38.51]].forEach(s => add(s[0], 4, 'SD-HAW', s[1], s[2], s[3], s[4], { urban: true, pack: 'SD' }));
  add('SD-HAW-MN-K01', 6, 'SD-HAW-MN', 'Piassa area', 'ፒያሳ', 7.061, 38.478, { urban: true, pack: 'SD' });
  add('SD-HAWZ', 3, 'SD', 'Hawassa Zuria woreda (rural)', 'ሀዋሳ ዙሪያ', 7.0, 38.4, { urban: false, pack: 'SD' });
  add('SD-HAWZ-K01', 6, 'SD-HAWZ', 'Dore Bafeno kebele', 'ዶሬ ባፈኖ', 7.02, 38.42, { urban: false, pack: 'SD' });
  add('SD-HAWZ-K02', 6, 'SD-HAWZ', 'Jara Gelalcha kebele', 'ጃራ ገላልቻ', 6.98, 38.39, { urban: false, pack: 'SD' });
  // Mekelle sub-cities
  [['TG-MEK-AY','Ayder','ዓይደር',13.49,39.48],['TG-MEK-HD','Hadnet','ሓድነት',13.5,39.46],['TG-MEK-HW','Hawelti','ሓወልቲ',13.5,39.47],['TG-MEK-KW','Kedamay Weyane','ቀዳማይ ወያነ',13.49,39.47],['TG-MEK-QH','Quiha','ቁሓ',13.46,39.52],['TG-MEK-SM','Semien','ሰሜን',13.51,39.47],['TG-MEK-AH','Adi Haki','ዓዲ ሓቂ',13.48,39.46]].forEach(s => add(s[0], 4, 'TG-MEK', s[1], s[2], s[3], s[4], { urban: true, pack: 'TG' }));
  // Jigjiga kebeles (numbered, as used locally)
  for (let k = 1; k <= 4; k++) add('SM-JIG-K' + pad2(k), 6, 'SM-JIG', 'Jigjiga Kebele ' + pad2(k), 'Kebele ' + pad2(k), 9.35 + k * 0.004, 42.8 + k * 0.004, { urban: true, pack: 'SM' });
  // Adama kebeles and a rural Oromia woreda (Ada'a)
  for (let k = 1; k <= 3; k++) add('OR-ADAMA-K' + pad2(k), 6, 'OR-ADAMA', 'Adama Kebele ' + pad2(k), 'Ganda ' + pad2(k), 8.54 + k * 0.004, 39.27 + k * 0.004, { urban: true, pack: 'OR' });
  add('OR-ESZ', 2, 'OR', 'East Shewa zone', 'Godina Shawaa Bahaa', 8.6, 39.1, { urban: false, pack: 'OR' });
  add('OR-ESZ-ADAA', 3, 'OR-ESZ', "Ada'a woreda (rural)", "Aanaa Adaa'aa", 8.7, 39.0, { urban: false, pack: 'OR' });
  add('OR-ESZ-ADAA-K01', 6, 'OR-ESZ-ADAA', 'Ude kebele', 'Ganda Udee', 8.72, 39.02, { urban: false, pack: 'OR' });
  add('OR-ESZ-ADAA-K02', 6, 'OR-ESZ-ADAA', 'Dire kebele', 'Ganda Dirree', 8.68, 38.98, { urban: false, pack: 'OR' });
  return U;
}
function pad2(n) { return (n < 10 ? '0' : '') + n; }

const SEED = {
  version: SEED_VERSION,
  geo: _geoBuild(),

  emergency: [
    // Published public numbers (S7, S8). Owner confirmation must be recorded before the record shows "verified".
    { id: 'EM-ET-911', jurisdiction: 'ET', service: 'police', label: 'Police / general emergency', primary: '911', backup: '991', hours: '24/7', languages: ['am','en'], owner: 'Ethiopian Federal Police', source: 'UK FCDO travel advice (S8)', sourceUrl: 'https://www.gov.uk/foreign-travel-advice/ethiopia/getting-help', status: 'source-checked', verifiedAt: SEED_DATE, verifiedBy: 'seed', reviewDue: '2026-12-01' },
    { id: 'EM-AA-907', jurisdiction: 'AA', service: 'ambulance', label: 'Ambulance (Addis Ababa)', primary: '907', backup: '', hours: '24/7', languages: ['am','en'], owner: 'Addis Ababa emergency medical services', source: 'UK FCDO travel advice (S8)', sourceUrl: 'https://www.gov.uk/foreign-travel-advice/ethiopia/getting-help', status: 'source-checked', verifiedAt: SEED_DATE, verifiedBy: 'seed', reviewDue: '2026-12-01' },
    { id: 'EM-AA-939', jurisdiction: 'AA', service: 'fire', label: 'Fire and disaster (Addis Ababa)', primary: '939', backup: '', hours: '24/7', languages: ['am','en'], owner: 'Addis Ababa Fire and Disaster Risk Management Commission', source: 'addisfire.gov.et (S7)', sourceUrl: 'https://addisfire.gov.et/', status: 'source-checked', verifiedAt: SEED_DATE, verifiedBy: 'seed', reviewDue: '2026-12-01' },
    { id: 'EM-AA-945', jurisdiction: 'AA', service: 'traffic', label: 'Traffic police (Addis Ababa)', primary: '945', backup: '', hours: '24/7', languages: ['am'], owner: 'Addis Ababa Police Commission', source: 'Public listings, to confirm', sourceUrl: '', status: 'pending', verifiedAt: null, verifiedBy: null, reviewDue: '2026-10-01' },
    { id: 'EM-SD-HOSP', jurisdiction: 'SD', service: 'hospital', label: 'Hawassa University Comprehensive Specialized Hospital, emergency', primary: '', backup: '', hours: '24/7', languages: ['am','en'], owner: 'Hawassa University', source: 'Hawassa City Administration (S9), number to be obtained from owner', sourceUrl: 'https://www.hawassa.gov.et/sdm', status: 'pending', verifiedAt: null, verifiedBy: null, reviewDue: '2026-10-01' },
    { id: 'EM-HR-CITY', jurisdiction: 'HR', service: 'police', label: 'Harar city emergency services', primary: '', backup: '', hours: '24/7', languages: ['am','so'], owner: 'Harari Regional State', source: 'harari.gov.et (S10), number to be obtained from owner', sourceUrl: 'https://www.harari.gov.et/en', status: 'pending', verifiedAt: null, verifiedBy: null, reviewDue: '2026-10-01' },
    { id: 'EM-SM-HOSP', jurisdiction: 'SM', service: 'hospital', label: 'Karamara General Hospital (Jigjiga), emergency', primary: '', backup: '', hours: '24/7', languages: ['so','am'], owner: 'Somali Regional Health Bureau', source: 'To be obtained from owner', sourceUrl: '', status: 'pending', verifiedAt: null, verifiedBy: null, reviewDue: '2026-10-01' },
    { id: 'EM-TG-HOSP', jurisdiction: 'TG', service: 'hospital', label: 'Ayder Comprehensive Specialized Hospital (Mekelle), emergency', primary: '', backup: '', hours: '24/7', languages: ['ti','am','en'], owner: 'Mekelle University', source: 'To be obtained from owner', sourceUrl: '', status: 'pending', verifiedAt: null, verifiedBy: null, reviewDue: '2026-10-01' }
  ],

  facilities: [
    // Public referral hospitals in pilot catchments (names public; coordinates approximate; MFR ID to be matched, ToR §8)
    { id: 'F-AA-TASH', name: 'Tikur Anbessa (Black Lion) Specialized Hospital', type: 'hospital', adminUnit: 'AA-LID', lat: 9.019, lng: 38.748, coordsValidated: false, services: ['emergency','surgery','maternity','paediatrics','icu'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public federal hospital; MFR match pending' }, languages: ['am','en'] },
    { id: 'F-AA-STP', name: "St. Paul's Hospital Millennium Medical College", type: 'hospital', adminUnit: 'AA-GUL', lat: 9.056, lng: 38.735, coordsValidated: false, services: ['emergency','surgery','maternity','paediatrics','icu'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public federal hospital; MFR match pending' }, languages: ['am','en'] },
    { id: 'F-AA-ZEW', name: 'Zewditu Memorial Hospital', type: 'hospital', adminUnit: 'AA-KIR', lat: 9.012, lng: 38.757, coordsValidated: false, services: ['emergency','general','maternity'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public city hospital; MFR match pending' }, languages: ['am','en'] },
    { id: 'F-AA-Y12', name: 'Yekatit 12 Hospital Medical College', type: 'hospital', adminUnit: 'AA-ARA', lat: 9.036, lng: 38.755, coordsValidated: false, services: ['emergency','general','burns','maternity'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public city hospital; MFR match pending' }, languages: ['am','en'] },
    { id: 'F-AA-BOLEHC', name: 'Bole Health Centre (demo)', type: 'health-centre', adminUnit: 'AA-BOL-W01', lat: 8.994, lng: 38.792, coordsValidated: false, services: ['general','maternity','vaccination'], emergencyCapable: false, hours: 'Mon-Sat 08:00-17:00', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['am'] },
    { id: 'F-SD-HUCSH', name: 'Hawassa University Comprehensive Specialized Hospital', type: 'hospital', adminUnit: 'SD-HAW-MS', lat: 7.049, lng: 38.494, coordsValidated: false, services: ['emergency','surgery','maternity','paediatrics','icu'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public university hospital; MFR match pending' }, languages: ['am','en'] },
    { id: 'F-SD-ADARE', name: 'Adare General Hospital', type: 'hospital', adminUnit: 'SD-HAW-MN', lat: 7.062, lng: 38.476, coordsValidated: false, services: ['emergency','general','maternity'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'pending', verifiedAt: null, by: null, evidence: '' }, languages: ['am'] },
    { id: 'F-TG-AYDER', name: 'Ayder Comprehensive Specialized Hospital', type: 'hospital', adminUnit: 'TG-MEK-AY', lat: 13.489, lng: 39.483, coordsValidated: false, services: ['emergency','surgery','maternity','paediatrics','icu'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public university hospital; MFR match pending' }, languages: ['ti','am','en'] },
    { id: 'F-SM-KARA', name: 'Karamara General Hospital', type: 'hospital', adminUnit: 'SM-JIG', lat: 9.352, lng: 42.795, coordsValidated: false, services: ['emergency','general','maternity','paediatrics'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public regional hospital; MFR match pending' }, languages: ['so','am'] },
    { id: 'F-OR-ADAMA', name: 'Adama Hospital Medical College', type: 'hospital', adminUnit: 'OR-ADAMA', lat: 8.545, lng: 39.268, coordsValidated: false, services: ['emergency','surgery','maternity','paediatrics'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Public referral hospital; MFR match pending' }, languages: ['om','am'] },
    { id: 'F-OR-UDEHC', name: 'Ude Health Centre (demo)', type: 'health-centre', adminUnit: 'OR-ESZ-ADAA-K01', lat: 8.72, lng: 39.02, coordsValidated: false, services: ['general','maternity','vaccination'], emergencyCapable: false, hours: 'Mon-Sat 08:00-17:00', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['om'] },
    { id: 'F-DD-DIL', name: 'Dilchora Referral Hospital', type: 'hospital', adminUnit: 'DD-DIRE', lat: 9.6, lng: 41.86, coordsValidated: false, services: ['emergency','surgery','maternity'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'pending', verifiedAt: null, by: null, evidence: '' }, languages: ['am','so'] },
    { id: 'F-HR-HF', name: 'Hiwot Fana Specialized University Hospital', type: 'hospital', adminUnit: 'HR-HAR', lat: 9.31, lng: 42.12, coordsValidated: false, services: ['emergency','surgery','maternity'], emergencyCapable: true, hours: '24/7', phone: '', registryId: '', licence: { status: 'public-facility', expiry: null }, verification: { state: 'pending', verifiedAt: null, by: null, evidence: '' }, languages: ['am','so'] },
    // Pharmacies (FICTIONAL demonstration records)
    { id: 'PH-AA-1', name: 'Medhanialem Community Pharmacy (demo)', type: 'pharmacy', adminUnit: 'AA-BOL-W01-K01', lat: 8.996, lng: 38.791, coordsValidated: true, services: ['dispensing','otc','delivery'], emergencyCapable: false, hours: 'Daily 08:00-22:00', phone: '+251 911 000 001', registryId: 'EFDA-DEMO-0001', responsiblePharmacist: 'Ph. Bethlehem Worku', licence: { no: 'PH/AA/DEMO/001', status: 'active', expiry: '2027-06-30' }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['am','en'], delivery: true, deliveryRadiusKm: 5 },
    { id: 'PH-AA-2', name: 'Kazanchis Pharmacy (demo)', type: 'pharmacy', adminUnit: 'AA-KIR-W01-K01', lat: 9.017, lng: 38.771, coordsValidated: true, services: ['dispensing','otc'], emergencyCapable: false, hours: 'Mon-Sat 08:00-20:00', phone: '+251 911 000 002', registryId: 'EFDA-DEMO-0002', responsiblePharmacist: 'Ph. Dawit Haile', licence: { no: 'PH/AA/DEMO/002', status: 'active', expiry: '2027-03-31' }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['am'], delivery: false },
    { id: 'PH-AA-3', name: 'Gerji Family Pharmacy (demo)', type: 'pharmacy', adminUnit: 'AA-BOL-W02-K01', lat: 8.995, lng: 38.812, coordsValidated: true, services: ['dispensing','otc'], emergencyCapable: false, hours: 'Daily 07:00-23:00', phone: '+251 911 000 003', registryId: '', responsiblePharmacist: 'Ph. Ruth Negash', licence: { no: 'PH/AA/DEMO/003', status: 'pending', expiry: '2026-09-15' }, verification: { state: 'pending', verifiedAt: null, by: null, evidence: 'Licence copy uploaded' }, languages: ['am','en'], delivery: true, deliveryRadiusKm: 3 },
    { id: 'PH-SD-1', name: 'Hawassa Piassa Pharmacy (demo)', type: 'pharmacy', adminUnit: 'SD-HAW-MN-K01', lat: 7.061, lng: 38.479, coordsValidated: true, services: ['dispensing','otc','delivery'], emergencyCapable: false, hours: 'Daily 08:00-21:00', phone: '+251 911 000 004', registryId: 'EFDA-DEMO-0004', responsiblePharmacist: 'Ph. Tigist Lemma', licence: { no: 'PH/SD/DEMO/004', status: 'active', expiry: '2027-01-31' }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['am','en'], delivery: true, deliveryRadiusKm: 4 },
    { id: 'PH-SM-1', name: 'Jigjiga Central Pharmacy (demo)', type: 'pharmacy', adminUnit: 'SM-JIG-K02', lat: 9.356, lng: 42.804, coordsValidated: true, services: ['dispensing','otc'], emergencyCapable: false, hours: 'Sat-Thu 08:00-20:00', phone: '+251 911 000 005', registryId: 'EFDA-DEMO-0005', responsiblePharmacist: 'Ph. Hodan Abdi', licence: { no: 'PH/SM/DEMO/005', status: 'active', expiry: '2027-05-31' }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['so','am'], delivery: false },
    { id: 'PH-TG-1', name: 'Ayder Pharmacy (demo)', type: 'pharmacy', adminUnit: 'TG-MEK-AY', lat: 13.49, lng: 39.481, coordsValidated: true, services: ['dispensing','otc'], emergencyCapable: false, hours: 'Daily 08:00-21:00', phone: '+251 911 000 006', registryId: 'EFDA-DEMO-0006', responsiblePharmacist: 'Ph. Kidane Tesfay', licence: { no: 'PH/TG/DEMO/006', status: 'active', expiry: '2027-04-30' }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['ti','am'], delivery: true, deliveryRadiusKm: 3 },
    { id: 'PH-OR-1', name: 'Adama Nagaa Pharmacy (demo)', type: 'pharmacy', adminUnit: 'OR-ADAMA-K01', lat: 8.544, lng: 39.274, coordsValidated: true, services: ['dispensing','otc'], emergencyCapable: false, hours: 'Daily 08:00-21:00', phone: '+251 911 000 007', registryId: 'EFDA-DEMO-0007', responsiblePharmacist: 'Ph. Gemechu Bekele', licence: { no: 'PH/OR/DEMO/007', status: 'active', expiry: '2027-02-28' }, verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demonstration record' }, languages: ['om','am'], delivery: false }
  ],

  practitioners: [
    // FICTIONAL demonstration records
    { id: 'PR-1', name: 'Dr. Selamawit Bekele', profession: 'doctor', specialty: 'General practitioner', scope: ['general','maternal','chronic','medication','srh'], gender: 'f', languages: ['am','en'], licence: { no: 'MD/AA/DEMO/1001', issuer: 'MOH HRL', status: 'active', issued: '2024-01-15', expiry: '2027-01-14' }, facility: 'F-AA-BOLEHC', adminUnit: 'AA-BOL', lat: 8.994, lng: 38.792, serviceArea: 'Bole and Yeka sub-cities', modes: ['secure_chat','phone_audio','by_appointment'], availability: 'available_now', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'General practice, women\'s health and chronic disease follow-up.' },
    { id: 'PR-2', name: 'Dr. Yonas Tesfaye', profession: 'doctor', specialty: 'Paediatrician', scope: ['child','general'], gender: 'm', languages: ['am','en'], licence: { no: 'MD/AA/DEMO/1002', issuer: 'MOH HRL', status: 'active', issued: '2023-06-01', expiry: '2026-11-30' }, facility: 'F-AA-Y12', adminUnit: 'AA-ARA', lat: 9.036, lng: 38.755, serviceArea: 'Addis Ababa', modes: ['secure_chat','by_appointment'], availability: 'by_appointment', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Child health, fever, nutrition and vaccination questions.' },
    { id: 'PR-3', name: 'Sr. Hiwot Alemu', profession: 'midwife', specialty: 'Midwife', scope: ['maternal','srh'], gender: 'f', languages: ['am'], licence: { no: 'MW/AA/DEMO/2001', issuer: 'MOH HRL', status: 'active', issued: '2024-03-01', expiry: '2027-02-28' }, facility: 'F-AA-BOLEHC', adminUnit: 'AA-BOL', lat: 8.99, lng: 38.79, serviceArea: 'Bole sub-city, home visits woredas 01-03', modes: ['home_visit','phone_audio','secure_chat'], availability: 'available_now', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Antenatal and postnatal follow-up, breastfeeding support.' },
    { id: 'PR-4', name: 'Dr. Abdirahman Mohamed', profession: 'doctor', specialty: 'General practitioner', scope: ['general','child','chronic','medication'], gender: 'm', languages: ['so','am','en'], licence: { no: 'MD/SM/DEMO/1003', issuer: 'Somali RHB', status: 'active', issued: '2022-09-01', expiry: '2026-10-15' }, facility: 'F-SM-KARA', adminUnit: 'SM-JIG', lat: 9.352, lng: 42.795, serviceArea: 'Jigjiga city and Fafan zone', modes: ['phone_audio','secure_chat','by_appointment'], availability: 'available_now', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'General medicine, Somali-language consultations.' },
    { id: 'PR-5', name: 'Dr. Tsehaye Gebremedhin', profession: 'doctor', specialty: 'Internist', scope: ['general','chronic','medication'], gender: 'f', languages: ['ti','am','en'], licence: { no: 'MD/TG/DEMO/1004', issuer: 'Tigray RHB', status: 'active', issued: '2023-01-10', expiry: '2027-01-09' }, facility: 'F-TG-AYDER', adminUnit: 'TG-MEK-AY', lat: 13.489, lng: 39.483, serviceArea: 'Mekelle', modes: ['secure_chat','by_appointment'], availability: 'by_appointment', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Diabetes, hypertension and chronic care.' },
    { id: 'PR-6', name: 'Dr. Chaltu Gemechu', profession: 'doctor', specialty: 'General practitioner', scope: ['general','maternal','child','srh','medication'], gender: 'f', languages: ['om','am','en'], licence: { no: 'MD/OR/DEMO/1005', issuer: 'Oromia RHB', status: 'active', issued: '2024-05-01', expiry: '2027-04-30' }, facility: 'F-OR-ADAMA', adminUnit: 'OR-ADAMA', lat: 8.545, lng: 39.268, serviceArea: "Adama city and Ada'a woreda", modes: ['phone_audio','secure_chat','home_visit'], availability: 'available_now', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Family medicine in Afaan Oromo and Amharic.' },
    { id: 'PR-7', name: 'Nurse Meseret Tadesse', profession: 'nurse', specialty: 'Community nurse', scope: ['general','child','chronic'], gender: 'f', languages: ['am','en'], licence: { no: 'RN/SD/DEMO/3001', issuer: 'Sidama RHB', status: 'active', issued: '2023-11-01', expiry: '2026-09-20' }, facility: 'F-SD-ADARE', adminUnit: 'SD-HAW-MN', lat: 7.062, lng: 38.476, serviceArea: 'Hawassa city and Hawassa Zuria', modes: ['home_visit','phone_audio'], availability: 'available_now', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Wound care, home nursing and chronic-care follow-up.' },
    { id: 'PR-8', name: 'Dr. Mulugeta Kassa', profession: 'doctor', specialty: 'Psychiatrist', scope: ['mental','general'], gender: 'm', languages: ['am','en'], licence: { no: 'MD/AA/DEMO/1006', issuer: 'MOH HRL', status: 'active', issued: '2021-02-01', expiry: '2026-12-31' }, facility: 'F-AA-STP', adminUnit: 'AA-GUL', lat: 9.056, lng: 38.735, serviceArea: 'Addis Ababa', modes: ['secure_chat','phone_audio','by_appointment'], availability: 'by_appointment', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Mental wellbeing, anxiety, depression and sleep.' },
    { id: 'PR-9', name: 'Dr. Lidya Girma', profession: 'doctor', specialty: 'Gynaecologist', scope: ['maternal','srh','general'], gender: 'f', languages: ['am','en','fr'], licence: { no: 'MD/AA/DEMO/1007', issuer: 'MOH HRL', status: 'active', issued: '2020-08-01', expiry: '2026-09-05' }, facility: 'F-AA-ZEW', adminUnit: 'AA-KIR', lat: 9.012, lng: 38.757, serviceArea: 'Addis Ababa', modes: ['secure_chat','by_appointment'], availability: 'on_leave', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo', evidence: 'Demo' }, bio: 'Women\'s health, contraception and menstrual disorders.' },
    { id: 'PR-10', name: 'Dr. Samuel Fekadu', profession: 'doctor', specialty: 'General practitioner', scope: ['general'], gender: 'm', languages: ['am'], licence: { no: 'MD/AA/DEMO/1008', issuer: 'MOH HRL', status: 'pending', issued: '', expiry: '' }, facility: '', adminUnit: 'AA-YEK', lat: 9.05, lng: 38.8, serviceArea: 'Yeka', modes: ['secure_chat'], availability: 'offline_mode', verification: { state: 'pending', verifiedAt: null, by: null, evidence: 'Licence number submitted, HRL check pending' }, bio: '' }
  ],

  pharmacyProducts: (() => {
    const base = [
      ['Paracetamol','500 mg','tablet','20','otc','analgesic',40],['Ibuprofen','400 mg','tablet','20','otc','analgesic',60],['Oral rehydration salts (ORS)','20.5 g','sachet','1','otc','rehydration',10],['Zinc sulfate','20 mg','tablet','10','otc','child',35],
      ['Amoxicillin','500 mg','capsule','21','pom','antibiotic',120],['Metformin','500 mg','tablet','30','pom','diabetes',90],['Amlodipine','5 mg','tablet','30','pom','hypertension',110],['Salbutamol inhaler','100 mcg/dose','inhaler','1','pom','respiratory',260],
      ['Iron + folic acid','60 mg / 400 mcg','tablet','30','otc','maternal',70],['Cetirizine','10 mg','tablet','10','otc','allergy',45],['Chlorhexidine','4%','solution 100 ml','1','otc','antiseptic',85],['Pregnancy test kit','','kit','1','otc','srh',60],['Insulin (human, mixed)','100 IU/ml','vial 10 ml','1','pom','diabetes',450]
    ];
    const retail = [['Liquid hand soap','250 ml','bottle','1','retail','personal-care',95],['Body lotion','200 ml','bottle','1','retail','beauty',180],['Baby wipes','','pack 80','1','retail','baby',120]];
    const states = ['available','available','limited','available','unavailable','available','expected','requires_confirmation','available','limited','available','available','not_stocked'];
    const out = []; let n = 1;
    ['PH-AA-1','PH-AA-2','PH-AA-3','PH-SD-1','PH-SM-1','PH-TG-1','PH-OR-1'].forEach((ph, pi) => {
      base.forEach((b, i) => {
        const st = states[(i + pi) % states.length];
        const ageH = (i * 7 + pi * 11) % 120; // hours since update, some deliberately stale (> 72 h)
        out.push({ id: 'PP-' + (n++), pharmacy: ph, generic: b[0], brand: '', strength: b[1], form: b[2], pack: b[3], rx: b[4], category: b[5], price: b[6] + pi * 5, stock: st, expectedDate: st === 'expected' ? '2026-09-05' : '', updatedAt: new Date(Date.now() - ageH * 3600e3).toISOString() });
      });
      if (pi === 0 || pi === 3) retail.forEach(r => out.push({ id: 'PP-' + (n++), pharmacy: ph, generic: r[0], brand: '', strength: r[1], form: r[2], pack: r[3], rx: r[4], category: r[5], price: r[6], stock: 'available', expectedDate: '', updatedAt: new Date().toISOString() }));
    });
    return out;
  })(),

  hansProducts: [
    { id: 'HP-1', name: 'Reusable sanitary pads (pack of 3)', category: 'menstrual', variants: [{ sku: 'RSP-REG', label: 'Regular', price: 350 }, { sku: 'RSP-HVY', label: 'Heavy flow', price: 380 }, { sku: 'RSP-NGT', label: 'Night', price: 420 }], stock: 'available', education: { use: 'Place the pad on underwear with the soft side up and fasten the wings. Change every 4 to 6 hours or when full. Rinse in cold water first, wash with mild soap, dry fully in the sun. Lasts 12 to 24 months with care.', safety: 'Do not use bleach. Dry completely before storing. Stop using and consult a health worker if you notice irritation.' }, audioKey: 'edu_pads' },
    { id: 'HP-2', name: 'Period underwear', category: 'menstrual', variants: [{ sku: 'PU-S', label: 'S', price: 550 }, { sku: 'PU-M', label: 'M', price: 550 }, { sku: 'PU-L', label: 'L', price: 550 }, { sku: 'PU-XL', label: 'XL', price: 580 }], stock: 'available', education: { use: 'Wear like normal underwear for light to medium days or with a pad on heavy days. Rinse in cold water after use, machine or hand wash, air dry.', safety: 'Do not iron or tumble dry. Replace when the absorbent layer thins.' }, audioKey: 'edu_underwear' },
    { id: 'HP-3', name: 'Adult diapers', category: 'adult-care', variants: [{ sku: 'AD-M', label: 'M', price: 620 }, { sku: 'AD-L', label: 'L', price: 660 }, { sku: 'AD-XL', label: 'XL', price: 700 }], stock: 'available', education: { use: 'Check size by waist measurement. Change promptly when wet to protect the skin. Clean and dry the skin at each change.', safety: 'Seek a health worker if you notice redness, sores or fever.' }, audioKey: 'edu_adult' },
    { id: 'HP-4', name: 'Incontinence pads', category: 'adult-care', variants: [{ sku: 'IP-STD', label: 'Standard (pack of 10)', price: 300 }], stock: 'limited', education: { use: 'Fix inside close-fitting underwear. Change when wet.', safety: 'Not for use as a wound dressing.' }, audioKey: 'edu_incont' },
    { id: 'HP-5', name: 'Washable bed protector', category: 'adult-care', variants: [{ sku: 'BP-90', label: '90 x 75 cm', price: 480 }], stock: 'available', education: { use: 'Place absorbent side up under the person. Wash at 60 degrees, air dry.', safety: 'Replace if the waterproof layer cracks.' }, audioKey: 'edu_bed' }
  ],

  wellbeing: [
    { id: 'WB-1', name: 'Mimi Home Massage (demo)', service: 'Home massage', gender: 'f', languages: ['am','en'], adminUnit: 'AA-BOL', lat: 8.99, lng: 38.79, serviceArea: 'Bole, Yeka, Kirkos', availability: 'by_appointment', price: 'From 900 ETB / hour', safeguards: 'ID checked at booking; check-in/out with the platform; a trusted contact can be notified.', cancelTerms: 'Free cancellation up to 6 hours before.', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo' }, photo: '' },
    { id: 'WB-2', name: 'FitHome Coaching (demo)', service: 'Home fitness training', gender: 'm', languages: ['am','en'], adminUnit: 'AA-KIR', lat: 9.01, lng: 38.76, serviceArea: 'Central Addis Ababa', availability: 'available_now', price: '700 ETB / session', safeguards: 'ID checked; sessions can be outdoors or in shared spaces on request.', cancelTerms: '50% fee within 3 hours of the session.', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo' }, photo: '' },
    { id: 'WB-3', name: 'Hawassa Lakeside Yoga (demo)', service: 'Yoga and wellbeing coaching', gender: 'f', languages: ['am','en'], adminUnit: 'SD-HAW', lat: 7.05, lng: 38.47, serviceArea: 'Hawassa city', availability: 'by_appointment', price: '400 ETB / class', safeguards: 'Group classes in public venues; ID checked for home sessions.', cancelTerms: 'Free cancellation up to 12 hours before.', verification: { state: 'verified', verifiedAt: SEED_DATE, by: 'seed-demo' }, photo: '' },
    { id: 'WB-4', name: 'Adama Sport Coaching (demo)', service: 'Sport coaching (youth and adults)', gender: 'm', languages: ['om','am'], adminUnit: 'OR-ADAMA', lat: 8.54, lng: 39.27, serviceArea: 'Adama', availability: 'available_now', price: '300 ETB / session', safeguards: 'Sessions in public sports grounds only.', cancelTerms: 'Free cancellation.', verification: { state: 'pending', verifiedAt: null, by: null }, photo: '' }
  ],

  // Curated, versioned knowledge base for the guide (ToR §10). Approved items only; each with source and date.
  kb: [
    { id: 'KB-1', tags: ['emergency','danger','signs'], version: '1.0', approvedBy: 'Clinical safety group (demo)', approvedAt: SEED_DATE, source: 'WHO IMAI/IMCI danger signs, general guidance', title: { en: 'When is it an emergency?', fr: 'Quand est-ce une urgence ?' }, body: { en: 'Call emergency services or go to the nearest emergency-capable facility now if there is: heavy bleeding, chest pain or pressure, difficulty breathing, unconsciousness or confusion, seizure, severe injury or burn, a suspected stroke (face drooping, arm weakness, speech difficulty), poisoning, severe abdominal pain in pregnancy, or thoughts of harming yourself. Do not wait for an online reply.', fr: 'Appelez les urgences ou allez à l\'établissement d\'urgence le plus proche en cas de : saignement abondant, douleur ou pression thoracique, difficulté à respirer, perte de connaissance ou confusion, convulsions, blessure ou brûlure grave, suspicion d\'AVC (visage affaissé, faiblesse du bras, trouble de la parole), empoisonnement, douleur abdominale sévère pendant la grossesse, ou pensées d\'automutilation. N\'attendez pas une réponse en ligne.' } },
    { id: 'KB-2', tags: ['period','pads','menstrual','wash','han\'s'], version: '1.0', approvedBy: "Han's With Care (demo)", approvedAt: SEED_DATE, source: "Han's With Care product guidance", title: { en: 'Using and washing reusable pads', fr: 'Utiliser et laver les serviettes réutilisables' }, body: { en: 'Change a reusable pad every 4 to 6 hours or when full. Rinse in cold water until the water runs clear, wash with mild soap, rinse again and dry fully, ideally in sunlight. Store dry. Pads last 12 to 24 months. Periods that are very heavy (soaking a pad every hour), last more than 7 days, or come with severe pain or fainting should be discussed with a health worker.', fr: 'Changez la serviette toutes les 4 à 6 heures ou quand elle est pleine. Rincez à l\'eau froide jusqu\'à ce que l\'eau soit claire, lavez au savon doux, rincez et séchez complètement, idéalement au soleil. Rangez au sec. Durée de vie 12 à 24 mois. Des règles très abondantes (une serviette trempée chaque heure), de plus de 7 jours, ou accompagnées de fortes douleurs ou d\'évanouissements doivent être discutées avec un soignant.' } },
    { id: 'KB-3', tags: ['pregnancy','maternal','antenatal','danger'], version: '1.0', approvedBy: 'Clinical safety group (demo)', approvedAt: SEED_DATE, source: 'WHO antenatal care recommendations (general)', title: { en: 'Pregnancy danger signs', fr: 'Signes de danger pendant la grossesse' }, body: { en: 'Seek care immediately for vaginal bleeding, severe headache with blurred vision, fits, high fever, severe abdominal pain, the waters breaking before 37 weeks, the baby moving much less, or labour lasting more than 12 hours. Attend at least 8 antenatal contacts and deliver with a skilled attendant.', fr: 'Consultez immédiatement en cas de saignement vaginal, forts maux de tête avec vision trouble, convulsions, forte fièvre, douleur abdominale sévère, perte des eaux avant 37 semaines, bébé qui bouge beaucoup moins, ou travail de plus de 12 heures. Faites au moins 8 consultations prénatales et accouchez avec un personnel qualifié.' } },
    { id: 'KB-4', tags: ['child','fever','diarrhoea','baby'], version: '1.0', approvedBy: 'Clinical safety group (demo)', approvedAt: SEED_DATE, source: 'WHO IMCI general danger signs', title: { en: 'Sick child: when to go now', fr: 'Enfant malade : quand consulter maintenant' }, body: { en: 'Take a child to a facility now if they cannot drink or breastfeed, vomit everything, have convulsions, are lethargic or unconscious, breathe fast or with difficulty, or have fever with a stiff neck or rash. For diarrhoea, give ORS and zinc and keep feeding; go now if there is blood in the stool or signs of dehydration.', fr: 'Emmenez l\'enfant maintenant s\'il ne peut pas boire ou téter, vomit tout, convulse, est léthargique ou inconscient, respire vite ou difficilement, ou a de la fièvre avec raideur de la nuque ou éruption. Pour la diarrhée, donnez SRO et zinc et continuez à nourrir ; consultez immédiatement en cas de sang dans les selles ou de déshydratation.' } },
    { id: 'KB-5', tags: ['prescription','pharmacy','medicine','dispensing'], version: '1.0', approvedBy: 'Pharmacy adviser (demo)', approvedAt: SEED_DATE, source: 'EFDA dispensing rules (general)', title: { en: 'Prescriptions and pharmacies on this platform', fr: 'Ordonnances et pharmacies sur cette plateforme' }, body: { en: 'You can send a photo of a prescription to verified pharmacies to check availability and choose collection or delivery. Only a licensed pharmacist decides if a prescription is valid and what can be dispensed. Prescription-only medicines are never sold without a valid prescription, and the platform never substitutes medicines or gives dosing advice.', fr: 'Vous pouvez envoyer la photo d\'une ordonnance à des pharmacies vérifiées pour connaître la disponibilité et choisir retrait ou livraison. Seul un pharmacien agréé décide de la validité et de la délivrance. Les médicaments sur ordonnance ne sont jamais vendus sans ordonnance valide et la plateforme ne substitue jamais un médicament ni ne conseille de dosage.' } },
    { id: 'KB-6', tags: ['platform','how','account','privacy','free'], version: '1.0', approvedBy: "Han's operations (demo)", approvedAt: SEED_DATE, source: 'Platform terms', title: { en: 'How this platform works', fr: 'Comment fonctionne la plateforme' }, body: { en: 'Browsing, emergency numbers and search are free and need no account. When you send a request or order, we ask only for a phone number, your consent and a location. Verified health workers respond from their own dashboard; you follow the status under My requests. The platform connects you to care; it does not replace a consultation.', fr: 'La consultation, les numéros d\'urgence et la recherche sont gratuits et sans compte. Pour une demande ou une commande, nous demandons seulement un numéro de téléphone, votre consentement et une localisation. Les soignants vérifiés répondent depuis leur tableau de bord ; suivez le statut dans Mes demandes. La plateforme vous met en relation avec des soins, elle ne remplace pas une consultation.' } },
    { id: 'KB-7', tags: ['mental','stress','sleep','anxiety','sad'], version: '1.0', approvedBy: 'Clinical safety group (demo)', approvedAt: SEED_DATE, source: 'WHO mhGAP general guidance', title: { en: 'Mental wellbeing support', fr: 'Soutien au bien-être mental' }, body: { en: 'Feeling low, anxious or unable to sleep for more than two weeks is a good reason to talk to a verified health worker. If you have thoughts of harming yourself, call emergency services or go to the nearest hospital now, and tell someone you trust.', fr: 'Se sentir déprimé, anxieux ou ne pas dormir pendant plus de deux semaines justifie de parler à un soignant vérifié. En cas de pensées d\'automutilation, appelez les urgences ou allez à l\'hôpital le plus proche maintenant, et parlez-en à une personne de confiance.' } },
    { id: 'KB-8', tags: ['adult','incontinence','diaper','elderly','skin'], version: '1.0', approvedBy: "Han's With Care (demo)", approvedAt: SEED_DATE, source: "Han's With Care product guidance", title: { en: 'Caring for an adult with incontinence', fr: 'Prendre soin d\'un adulte incontinent' }, body: { en: 'Change products promptly when wet, clean and dry the skin at each change, and check the skin daily. Redness that does not fade, sores, fever or pain when passing urine should be discussed with a health worker. New or sudden incontinence also deserves a consultation.', fr: 'Changez rapidement les protections mouillées, nettoyez et séchez la peau à chaque change, et vérifiez la peau chaque jour. Une rougeur persistante, des plaies, de la fièvre ou des douleurs en urinant doivent être signalées à un soignant. Une incontinence nouvelle ou soudaine mérite aussi une consultation.' } }
  ],

  // Clinician-approved red-flag rule layer (ToR §10). Evaluated BEFORE any guide dialogue and before matching.
  redFlags: [
    { id: 'RF-BLEED', label: 'severe bleeding', kw: { en: ['bleeding a lot','heavy bleeding','blood won\'t stop','bleeding heavily','haemorrhage','hemorrhage'], am: ['ብዙ ደም','ደም መፍሰስ','ደም እየፈሰሰ'], ti: ['ብዙሕ ደም','ደም ምፍሳስ'], om: ['dhiiga baay\'ee','dhiigni hin dhaabbanne'], so: ['dhiig badan','dhiigbax'], fr: ['saigne beaucoup','saignement abondant','hémorragie'] } },
    { id: 'RF-CHEST', label: 'chest pain', kw: { en: ['chest pain','chest pressure','heart attack'], am: ['የደረት ህመም','ደረቴ'], ti: ['ቃንዛ ኣፍልቢ'], om: ['dhukkubbii qomaa','qoma na dhukkuba'], so: ['xanuun laab','laabta'], fr: ['douleur thoracique','douleur à la poitrine','crise cardiaque'] } },
    { id: 'RF-BREATH', label: 'difficulty breathing', kw: { en: ['can\'t breathe','cannot breathe','difficulty breathing','struggling to breathe','choking','not breathing'], am: ['መተንፈስ አልቻልኩም','ትንፋሽ','እየተነፈሰ አይደለም'], ti: ['ምስትንፋስ ኣይክእልን'], om: ['hafuura baafachuu hin danda\'u','hafuurri'], so: ['neefsan kari','neefta'], fr: ['n\'arrive pas à respirer','difficulté à respirer','étouffe'] } },
    { id: 'RF-UNCON', label: 'unconscious or seizure', kw: { en: ['unconscious','not responding','passed out','fainted','seizure','convulsion','fit'], am: ['ራሱን ስቷል','ራሱን ሳተ','መንቀጥቀጥ','ንቃተ ህሊና'], ti: ['ንቕሓት ስኢኑ','ምንቅጥቃጥ'], om: ['of wallaale','hollachaa','miira dhabe'], so: ['miyir beel','suuxay','gariir'], fr: ['inconscient','évanoui','convulsion','ne répond pas'] } },
    { id: 'RF-POISON', label: 'poisoning', kw: { en: ['poison','swallowed','overdose','drank chemical'], am: ['መርዝ','ተመርዟል','መድሃኒት በብዛት'], ti: ['መርዚ','ተመሪዙ'], om: ['summii','summaa\'e'], so: ['sun','sumoobay'], fr: ['poison','empoisonn','surdose','avalé'] } },
    { id: 'RF-SELF', label: 'self-harm', kw: { en: ['kill myself','suicide','end my life','hurt myself','self-harm','want to die'], am: ['ራሴን ማጥፋት','ራሴን መግደል','መሞት እፈልጋለሁ'], ti: ['ነብሰይ ከጥፍእ','ክመውት እደሊ'], om: ['of ajjeesuu','du\'uu barbaada'], so: ['is dilo','naftayda','dhiman rabaa'], fr: ['me suicider','me tuer','mettre fin à mes jours','me faire du mal'] } },
    { id: 'RF-LABOUR', label: 'labour complication', kw: { en: ['in labour','in labor','waters broke','baby is coming','pregnant and bleeding','pregnant bleeding'], am: ['ምጥ','ውሃዬ ፈሰሰ','እርጉዝ ደም'], ti: ['ሕርሲ','ማይ ፈሲሱ'], om: ['ciniinsuu','bishaan cabe','ulfaa dhiiga'], so: ['foosha','biyaha dhacay','uur dhiig'], fr: ['en travail','perdu les eaux','enceinte et saigne'] } },
    { id: 'RF-INJURY', label: 'severe injury', kw: { en: ['accident','car crash','stabbed','shot','severe burn','broken bone','head injury','snake bite','snakebite'], am: ['አደጋ','መኪና ገጭቶኛል','ተወግቷል','ተቃጥሏል','እባብ ነደፈኝ'], ti: ['ሓደጋ','መኪና','ተወጊኡ','ተቓጺሉ','ተመን'], om: ['balaa konkolaataa','waraaname','gubate','bofa'], so: ['shil','baabuur','tooray','gubatay','abeeso'], fr: ['accident','brûlure grave','poignardé','fracture','morsure de serpent'] } },
    { id: 'RF-STROKE', label: 'stroke signs', kw: { en: ['stroke','face drooping','can\'t speak','arm weak','slurred'], am: ['ስትሮክ','ፊቱ ጠምዟል','መናገር አልቻለም'], ti: ['ስትሮክ','ገጹ ተጠዊዩ'], om: ['istirookii','fuulli jallate','dubbachuu hin danda\'u'], so: ['istaroog','wejiga','hadli kari'], fr: ['avc','visage affaissé','n\'arrive plus à parler'] } }
  ],

  // Demonstration accounts (ToR §5). Practitioners/pharmacies sign in without a password in the demo; administrators use a PIN.
  users: [
    { id: 'U-DR1', role: 'doctor', name: 'Dr. Selamawit Bekele', linked: 'PR-1' },
    { id: 'U-DR2', role: 'doctor', name: 'Dr. Yonas Tesfaye', linked: 'PR-2' },
    { id: 'U-MW1', role: 'nurse', name: 'Sr. Hiwot Alemu', linked: 'PR-3' },
    { id: 'U-DR4', role: 'doctor', name: 'Dr. Abdirahman Mohamed', linked: 'PR-4' },
    { id: 'U-DR6', role: 'doctor', name: 'Dr. Chaltu Gemechu', linked: 'PR-6' },
    { id: 'U-NU7', role: 'nurse', name: 'Nurse Meseret Tadesse', linked: 'PR-7' },
    { id: 'U-PH1', role: 'pharmacist', name: 'Ph. Bethlehem Worku', linked: 'PH-AA-1' },
    { id: 'U-PH2', role: 'pharmacist', name: 'Ph. Dawit Haile', linked: 'PH-AA-2' },
    { id: 'U-PH4', role: 'pharmacist', name: 'Ph. Tigist Lemma', linked: 'PH-SD-1' },
    { id: 'U-WB1', role: 'wellbeing', name: 'Mimi Home Massage', linked: 'WB-1' },
    { id: 'U-WB2', role: 'wellbeing', name: 'FitHome Coaching', linked: 'WB-2' },
    { id: 'U-ADM1', role: 'admin', name: 'Operations admin 1', pin: '2468' },
    { id: 'U-ADM2', role: 'admin', name: 'Operations admin 2', pin: '1357' },
    { id: 'U-VER1', role: 'verifier', name: 'Regulatory verifier', pin: '1111' },
    { id: 'U-SAF1', role: 'safety', name: 'Clinical safety officer', pin: '2222' },
    { id: 'U-DPO1', role: 'privacy', name: 'Privacy / DPO', pin: '3333' },
    { id: 'U-FIN1', role: 'finance', name: 'Finance admin', pin: '4444' }
  ],

  flags: { guide: true, whatsapp: true, telegram: true, map: true, wellbeing: true, products: true, pharmacy: true, voice: true, ratings: false, telebirr: false },
  fees: { pharmacySubscriptionMonthly: 0, shopSubscriptionMonthly: 0, wellbeingPlatformFeePct: 0, retailPlatformFeePct: 0, note: 'Pilot: all fees waived (ToR §21). Fees never influence verification or emergency ranking.' }
};
